#!/usr/bin/env python3
"""P42 UserPromptSubmit hook — Live Mycelium Bridge + Secret Sentinel.

Reads user prompt from stdin (JSON), checks for accidental secrets,
then runs bridge_fast() for activated concepts.

Auto-generated by muninn install_hooks(). Do not edit manually.
Target: <0.5s total execution time.
"""
import json
import math
import re
import sys
import os
import traceback
from datetime import datetime
from pathlib import Path


def _log_hook_error(context: str, exc: BaseException) -> None:
    """Append a swallowed exception to ~/.muninn/hook_errors.log.

    CHUNK A8 (2026-05-08): delegates to engine/core/_hook_logger which
    rotates the file (1 MB max, 3 backups) and falls back to stderr if
    the file is unwritable so the audit trail is never silently lost.
    """
    try:
        engine_core = str(Path(__file__).resolve().parent.parent.parent
                          / "engine" / "core")
        if engine_core not in sys.path:
            sys.path.insert(0, engine_core)
        from _hook_logger import log_hook_event
        log_hook_event("bridge_hook", context, exc)
    except Exception:
        # Last-resort fallback: write directly to stderr; hooks must exit 0.
        try:
            sys.stderr.write(
                f"[MUNINN HOOK LOG fallback] {datetime.now().isoformat()} "
                f"[bridge_hook:{context}] {type(exc).__name__}: {exc}\n"
            )
            sys.stderr.flush()
        except Exception:
            pass

def _shannon_entropy(s):
    """Shannon entropy of a string. High entropy = likely a secret."""
    if not s:
        return 0.0
    freq = {}
    for c in s:
        freq[c] = freq.get(c, 0) + 1
    length = len(s)
    return -sum((n / length) * math.log2(n / length) for n in freq.values())

def _has_char_diversity(s):
    """Check if string has mixed character classes (upper+lower+digit+special)."""
    classes = 0
    if re.search(r'[a-z]', s): classes += 1
    if re.search(r'[A-Z]', s): classes += 1
    if re.search(r'[0-9]', s): classes += 1
    if re.search(r'[^a-zA-Z0-9\s]', s): classes += 1
    return classes >= 3

# CHUNK A6 (2026-05-08): word boundaries + tighter entropy threshold to
# reduce cry-wolf false positives observed live during the audit session.
# - `\b` boundaries so "secret" matches the word, not "secretariat".
# - Removed bare `auth` (too common in technical prose); kept `auth_token`,
#   `api_key` (still matched via `api.?key`).
# - Entropy threshold raised 2.8 -> 3.5 in the trigger-adjacent path
#   (real passwords/hashes are ~3.5+; common English words are ~2.0-2.8).
_SECRET_TRIGGERS = re.compile(
    r'\b(?:cl[eé]|password|mdp|mot de passe|passwd|secret|passphrase'
    r'|api.?key|credentials?|auth_token|auth_key)\b',
    re.IGNORECASE
)

def _check_secrets(prompt):
    """Detect if user accidentally typed a password/key in their prompt.
    Returns warning string or None."""
    # 1. Check known API key patterns (structural)
    _API_PATTERNS = [
        r'ghp_[A-Za-z0-9]{20,}', r'sk-[A-Za-z0-9\-._]{20,}',
        r'AKIA[A-Z0-9]{16}', r'Bearer\s+[A-Za-z0-9\-._~+/]+=*',
    ]
    for pat in _API_PATTERNS:
        if re.search(pat, prompt):
            return "[MUNINN SENTINEL] API key/token detected in your message. It will be stored in the Claude transcript. Consider rotating it."

    # 2. Check for password-like strings near trigger words
    # A6: tightened entropy threshold from 2.8 -> 3.5 to avoid common words
    if _SECRET_TRIGGERS.search(prompt):
        words = prompt.split()
        for word in words:
            clean = word.strip('.,;:!?\'"/()[]{}')
            if len(clean) >= 6 and _has_char_diversity(clean) and _shannon_entropy(clean) > 3.5:
                return "[MUNINN SENTINEL] You may have typed a password or secret in your message. It will be recorded in the Claude transcript (.jsonl). Consider changing it. Muninn will redact it from .mn files but CANNOT erase it from the raw transcript."

    # 3. Standalone high-entropy check (no trigger needed) for very suspicious strings
    for word in prompt.split():
        clean = word.strip('.,;:!?\'"/()[]{}')
        if len(clean) >= 10 and _has_char_diversity(clean) and _shannon_entropy(clean) > 3.5:
            return "[MUNINN SENTINEL] High-entropy string detected — possible password or key. It will be stored in the raw transcript."

    return None

def main():
    # Empty stdin (manual run, tty mode, no pipe) is not an error — exit silently.
    # Without this guard the JSON decoder logged ~40 false-alarm entries per
    # day of testing into ~/.muninn/hook_errors.log (audit 2026-05-08).
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
    except UnicodeDecodeError as e:
        _log_hook_error("stdin_decode", e)
        sys.exit(0)
    except Exception as e:
        _log_hook_error("stdin_read", e)
        sys.exit(0)
    if not raw.strip():
        sys.exit(0)
    try:
        hook_input = json.loads(raw)
    except json.JSONDecodeError as e:
        _log_hook_error("stdin_parse", e)
        sys.exit(0)
    except Exception as e:
        _log_hook_error("stdin_unexpected", e)
        sys.exit(0)

    # Audit 2026-04-10: payload could be a list/str/None when stdin is
    # malformed JSON. .get() would crash. Type-check before using.
    if not isinstance(hook_input, dict):
        sys.exit(0)

    prompt = hook_input.get("prompt", "")
    if not prompt or not isinstance(prompt, str) or len(prompt) < 10:
        sys.exit(0)

    # Secret detection — runs FIRST, before anything else
    warning = _check_secrets(prompt)
    if warning:
        print(warning)
        sys.stdout.flush()

    repo_path = hook_input.get("cwd", os.getcwd())

    engine_core = str(Path(__file__).resolve().parent.parent.parent / "engine" / "core")
    if engine_core not in sys.path:
        sys.path.insert(0, engine_core)

    try:
        import muninn
        muninn._REPO_PATH = Path(repo_path).resolve()
        muninn._refresh_tree_paths()
        result = muninn.bridge_fast(prompt)
        if result:
            # Anti-Adversa clamp: refuse injection of any content containing
            # >30 chained shell commands. Defense-in-depth at the final
            # injection point. See docs/CLAUDE_CODE_LEAK_INTEL.md sec 10.
            try:
                from _secrets import clamp_chained_commands
                result, _ = clamp_chained_commands(result)
            except Exception as e:
                _log_hook_error("clamp_chained_commands", e)
            print(result)
    except Exception as e:
        _log_hook_error("bridge_fast", e)

    sys.exit(0)


if __name__ == "__main__":
    main()
