#!/usr/bin/env python3
"""P42 UserPromptSubmit hook — Live Mycelium Bridge.

Reads user prompt from stdin (JSON), runs bridge_fast(),
returns activated concepts as context for Claude.

Auto-generated by muninn install_hooks(). Do not edit manually.
Target: <0.5s total execution time.
"""
import json
import sys
import os
from pathlib import Path

def main():
    try:
        hook_input = json.loads(sys.stdin.read())
    except (json.JSONDecodeError, Exception):
        sys.exit(0)

    prompt = hook_input.get("prompt", "")
    if not prompt or len(prompt) < 10:
        sys.exit(0)

    repo_path = hook_input.get("cwd", os.getcwd())

    engine_core = str(Path(__file__).resolve().parent.parent.parent / "engine" / "core")
    if engine_core not in sys.path:
        sys.path.insert(0, engine_core)

    try:
        import muninn
        from pathlib import Path
        muninn._REPO_PATH = Path(repo_path).resolve()
        muninn._refresh_tree_paths()
        result = muninn.bridge_fast(prompt)
        if result:
            print(result)
    except Exception:
        pass

    sys.exit(0)


if __name__ == "__main__":
    main()
