#!/usr/bin/env python3
"""ConfigChange hook — log config file changes and validate Muninn paths.

Reads ConfigChange JSON payload from stdin (Claude Code spec):
  {
    "hook_event_name": "ConfigChange",
    "source": "user_settings|project_settings|local_settings|policy_settings|skills"
  }

When .claude/settings.local.json or .claude/rules/*.md change, log the
event to .muninn/config_changes.jsonl AND check that the Muninn hook
scripts referenced in the new settings still exist on disk (catches
broken settings.local.json early).

Cap log at 5000 entries.

Used for:
- Multi-dev teams editing shared config: catch when someone breaks the
  settings file
- Detecting unauthorized config tampering
- Re-syncing Muninn state after a config change

Design rules:
- Never raise. Exit 0 always.
- Atomic write via tempfile.
- The validation check is read-only — never mutates settings.

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import sys
import tempfile
from datetime import datetime
from pathlib import Path

MAX_ENTRIES = 5000


def _load_existing(log_path: Path) -> list:
    if not log_path.exists():
        return []
    try:
        out = []
        for line in log_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
        return out
    except OSError:
        return []


def _atomic_write_jsonl(log_path: Path, entries: list) -> None:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(
        dir=str(log_path.parent), suffix=".tmp", prefix=".cfg-"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            for entry in entries:
                f.write(json.dumps(entry, ensure_ascii=False) + "\n")
        os.replace(tmp, str(log_path))
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def _validate_hook_paths(repo_path: Path) -> dict:
    """Read settings.local.json and check that all hook command scripts exist.

    Returns {"valid": bool, "missing": [paths]}.
    """
    settings_path = repo_path / ".claude" / "settings.local.json"
    if not settings_path.exists():
        return {"valid": True, "missing": []}
    try:
        settings = json.loads(settings_path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {"valid": False, "missing": ["settings.local.json invalid JSON"]}

    missing = []
    hooks = settings.get("hooks", {})
    if not isinstance(hooks, dict):
        return {"valid": False, "missing": ["hooks key not a dict"]}

    def _walk_entries(entries):
        cmds = []
        for e in entries or []:
            if not isinstance(e, dict):
                continue
            if "command" in e:
                cmds.append(e["command"])
            elif "hooks" in e:
                for h in e.get("hooks", []):
                    if isinstance(h, dict) and "command" in h:
                        cmds.append(h["command"])
        return cmds

    for hook_name, entries in hooks.items():
        for cmd in _walk_entries(entries):
            # Try to extract a .py file path from the command
            # e.g.: 'python "C:/path/to/hook.py"' or 'python "/abs/path/hook.py"'
            for part in cmd.replace('"', " ").split():
                if part.endswith(".py"):
                    p = Path(part)
                    # Treat as a path-of-interest if it looks rooted:
                    #   - Windows drive letter (C:/, D:/...)
                    #   - Unix absolute path (/foo/bar)
                    #   - or pathlib says is_absolute
                    looks_rooted = (
                        p.is_absolute()
                        or part.startswith("/")
                        or (len(part) >= 2 and part[1] == ":")
                    )
                    if looks_rooted and not p.exists():
                        missing.append(f"{hook_name}: {part}")
                    break

    return {"valid": len(missing) == 0, "missing": missing}


def append_config_change(payload: dict, repo_path: Path) -> bool:
    if not isinstance(payload, dict):
        return False

    validation = _validate_hook_paths(Path(repo_path))

    entry = {
        "ts": datetime.now().isoformat(timespec="seconds"),
        "source": payload.get("source", "unknown"),
        "session_id": payload.get("session_id", ""),
        "valid_after": validation["valid"],
        "missing_paths": validation["missing"],
    }

    log_path = Path(repo_path) / ".muninn" / "config_changes.jsonl"
    existing = _load_existing(log_path)
    existing.append(entry)

    if len(existing) > MAX_ENTRIES:
        existing = existing[-MAX_ENTRIES:]

    _atomic_write_jsonl(log_path, existing)
    return True


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
        payload = json.loads(raw)
    except Exception:
        sys.exit(0)

    repo_path = payload.get("cwd") or os.getcwd()

    try:
        append_config_change(payload, Path(repo_path))
    except Exception:
        pass

    sys.exit(0)


if __name__ == "__main__":
    main()
