#!/usr/bin/env python3
"""Notification hook — append every Claude Code notification to audit log.

Reads Notification JSON payload from stdin (Claude Code spec):
  {
    "hook_event_name": "Notification",
    "message": "...",
    "title": "...",
    "notification_type": "permission_prompt|idle_prompt|auth_success|elicitation_dialog"
  }

Appends a structured entry to .muninn/audit_log.jsonl. One JSON object per
line. Cap at 10000 entries (drop oldest first when full).

Used for compliance / audit trails (SOC 2, ISO 27001, etc.) — answers
"who asked for what permission, when, on which repo".

Design rules:
- Never raise. Always exit 0. Audit trail failure must not block Claude.
- Atomic write via tempfile + os.replace.
- JSONL format (one obj per line) so it's append-friendly and tail-able.

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import sys
import tempfile
from datetime import datetime
from pathlib import Path


def _log_hook_error(context: str, exc: BaseException) -> None:
    """Append a swallowed exception to ~/.muninn/hook_errors.log.

    F5 (2026-05-10): delegates to engine/core/_hook_logger which
    rotates the file (1 MB max, 3 backups) and falls back to stderr if
    the file is unwritable so the audit trail is never silently lost.
    """
    try:
        engine_core = str(Path(__file__).resolve().parent.parent.parent
                          / "engine" / "core")
        if engine_core not in sys.path:
            sys.path.insert(0, engine_core)
        from _hook_logger import log_hook_event
        log_hook_event("notification_audit_hook", context, exc)
    except Exception:
        # Last-resort fallback: write directly to stderr; hooks must exit 0.
        try:
            sys.stderr.write(
                f"[MUNINN HOOK LOG fallback] {datetime.now().isoformat()} "
                f"[notification_audit_hook:{context}] {type(exc).__name__}: {exc}\n"
            )
            sys.stderr.flush()
        except Exception:
            pass


MAX_ENTRIES = 10000


def _load_existing(audit_path: Path) -> list:
    if not audit_path.exists():
        return []
    try:
        lines = audit_path.read_text(encoding="utf-8").splitlines()
        out = []
        for line in lines:
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
        return out
    except OSError:
        return []


def _atomic_write_jsonl(audit_path: Path, entries: list) -> None:
    audit_path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(
        dir=str(audit_path.parent), suffix=".tmp", prefix=".audit-"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            for entry in entries:
                f.write(json.dumps(entry, ensure_ascii=False) + "\n")
        os.replace(tmp, str(audit_path))
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def append_audit(payload: dict, repo_path: Path) -> bool:
    if not isinstance(payload, dict):
        return False

    entry = {
        "ts": datetime.now().isoformat(timespec="seconds"),
        "type": payload.get("notification_type", "unknown"),
        "title": payload.get("title", ""),
        "message": payload.get("message", "")[:500],  # cap message length
        "session_id": payload.get("session_id", ""),
    }

    audit_path = Path(repo_path) / ".muninn" / "audit_log.jsonl"
    existing = _load_existing(audit_path)
    existing.append(entry)

    if len(existing) > MAX_ENTRIES:
        existing = existing[-MAX_ENTRIES:]

    _atomic_write_jsonl(audit_path, existing)
    return True


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
    except UnicodeDecodeError as e:
        _log_hook_error("stdin_decode", e)
        sys.exit(0)
    except Exception as e:
        _log_hook_error("stdin_read", e)
        sys.exit(0)
    if not raw.strip():
        sys.exit(0)
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as e:
        _log_hook_error("stdin_parse", e)
        sys.exit(0)
    except Exception as e:
        _log_hook_error("stdin_unexpected", e)
        sys.exit(0)

    # Audit 2026-04-10: payload could be a list/str/None when stdin is
    # malformed JSON. .get() would crash. Type-check before using.
    if not isinstance(payload, dict):
        sys.exit(0)

    repo_path = payload.get("cwd") or os.getcwd()

    try:
        append_audit(payload, Path(repo_path))
    except Exception as e:
        _log_hook_error("append_audit", e)

    sys.exit(0)


if __name__ == "__main__":
    main()
