#!/usr/bin/env python3
"""Notification hook — append every Claude Code notification to audit log.

Reads Notification JSON payload from stdin (Claude Code spec):
  {
    "hook_event_name": "Notification",
    "message": "...",
    "title": "...",
    "notification_type": "permission_prompt|idle_prompt|auth_success|elicitation_dialog"
  }

Appends a structured entry to .muninn/audit_log.jsonl. One JSON object per
line. Cap at 10000 entries (drop oldest first when full).

Used for compliance / audit trails (SOC 2, ISO 27001, etc.) — answers
"who asked for what permission, when, on which repo".

Design rules:
- Never raise. Always exit 0. Audit trail failure must not block Claude.
- Atomic write via tempfile + os.replace.
- JSONL format (one obj per line) so it's append-friendly and tail-able.

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import sys
import tempfile
from datetime import datetime
from pathlib import Path

MAX_ENTRIES = 10000


def _load_existing(audit_path: Path) -> list:
    if not audit_path.exists():
        return []
    try:
        lines = audit_path.read_text(encoding="utf-8").splitlines()
        out = []
        for line in lines:
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
        return out
    except OSError:
        return []


def _atomic_write_jsonl(audit_path: Path, entries: list) -> None:
    audit_path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(
        dir=str(audit_path.parent), suffix=".tmp", prefix=".audit-"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            for entry in entries:
                f.write(json.dumps(entry, ensure_ascii=False) + "\n")
        os.replace(tmp, str(audit_path))
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def append_audit(payload: dict, repo_path: Path) -> bool:
    if not isinstance(payload, dict):
        return False

    entry = {
        "ts": datetime.now().isoformat(timespec="seconds"),
        "type": payload.get("notification_type", "unknown"),
        "title": payload.get("title", ""),
        "message": payload.get("message", "")[:500],  # cap message length
        "session_id": payload.get("session_id", ""),
    }

    audit_path = Path(repo_path) / ".muninn" / "audit_log.jsonl"
    existing = _load_existing(audit_path)
    existing.append(entry)

    if len(existing) > MAX_ENTRIES:
        existing = existing[-MAX_ENTRIES:]

    _atomic_write_jsonl(audit_path, existing)
    return True


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
        payload = json.loads(raw)
    except Exception:
        sys.exit(0)

    repo_path = payload.get("cwd") or os.getcwd()

    try:
        append_audit(payload, Path(repo_path))
    except Exception:
        pass

    sys.exit(0)


if __name__ == "__main__":
    main()
