#!/usr/bin/env python3
"""PostToolUseFailure hook — auto-feed errors.json from real-time tool failures.

Reads PostToolUseFailure JSON payload from stdin (Claude Code spec):
  {
    "hook_event_name": "PostToolUseFailure",
    "tool_name": "Bash",
    "tool_input": { "command": "...", ... },
    "tool_use_id": "toolu_...",
    "error": "Command exited with code 1: ...",
    "is_interrupt": false
  }

Appends a new entry to .muninn/errors.json in the existing P18 schema:
  {"error": "<tool>: <summary>", "fix": "", "date": "YYYY-MM-DD"}

Design rules:
- NEVER raise (always exit 0). A failing hook must not block Claude's session.
- NEVER write to stdout. PostToolUseFailure is non-blocking, output is logged
  to debug only — and we want to stay invisible.
- Atomic write via tempfile + os.replace.
- Dedup: skip if the last entry is identical (avoids spam on retried tools).
- Cap errors.json at 500 entries (drop oldest first).

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import sys
import tempfile
from datetime import datetime
from pathlib import Path


MAX_ENTRIES = 500


def _safe_summary(tool_name: str, error: str, max_len: int = 200) -> str:
    """Build a compact "<tool> | <error first line>" summary."""
    if not error:
        error = "(no error message)"
    first = error.splitlines()[0] if error else ""
    summary = f"{tool_name} | {first}"
    if len(summary) > max_len:
        summary = summary[: max_len - 3] + "..."
    return summary


def _load_existing(errors_path: Path) -> list:
    if not errors_path.exists():
        return []
    try:
        data = json.loads(errors_path.read_text(encoding="utf-8"))
        if isinstance(data, list):
            return data
        return []
    except (json.JSONDecodeError, OSError, ValueError):
        return []


def _atomic_write(errors_path: Path, data: list) -> None:
    errors_path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(
        dir=str(errors_path.parent), suffix=".tmp", prefix=".errors-"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        os.replace(tmp, str(errors_path))
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        # swallow — never raise from a hook


def feed_errors_json(payload: dict, repo_path: Path) -> bool:
    """Append a structured error entry. Returns True if a new entry was added.

    Pure function (no I/O on stdin/stdout). Importable for tests.
    """
    if not isinstance(payload, dict):
        return False

    tool_name = payload.get("tool_name", "")
    error_msg = payload.get("error", "")
    if not tool_name and not error_msg:
        return False

    errors_path = Path(repo_path) / ".muninn" / "errors.json"
    existing = _load_existing(errors_path)

    summary = _safe_summary(tool_name, error_msg)
    today = datetime.now().strftime("%Y-%m-%d")
    entry = {
        "error": summary,
        "fix": "",  # filled later by Sky/cousin via reflect cycle
        "date": today,
    }

    # Dedup: skip if last entry has identical error+date (retried tool)
    if existing and isinstance(existing[-1], dict):
        last = existing[-1]
        if last.get("error") == summary and last.get("date") == today:
            return False

    existing.append(entry)

    # Cap size — drop oldest entries first
    if len(existing) > MAX_ENTRIES:
        existing = existing[-MAX_ENTRIES:]

    _atomic_write(errors_path, existing)
    return True


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
        payload = json.loads(raw)
    except (json.JSONDecodeError, UnicodeDecodeError, Exception):
        sys.exit(0)

    repo_path = payload.get("cwd") or os.getcwd()

    try:
        feed_errors_json(payload, Path(repo_path))
    except Exception:
        pass

    sys.exit(0)


if __name__ == "__main__":
    main()
