#!/usr/bin/env python3
"""PostToolUse Edit/Write hook — log every successful file modification.

[DORMANT INTENTIONAL — I.3 (2026-05-12)]
This hook is shipped + copied to .claude/hooks/ by install_hooks() but
NOT auto-registered in settings.local.json. The intended consumer (audit
viewer reading .muninn/edits_log.jsonl) was never implemented. Kept as
opt-in scaffolding for Phase 3 enterprise pitch (compliance, drift).
Sky activates manually via direct settings.local.json edit when a
customer asks for an edit audit trail. H.0 garde-fou whitelist covers
this file (see WHITELIST_DORMANT_HOOKS in tests/test_h0_no_orphan.py).

Reads PostToolUse JSON payload from stdin (Claude Code spec):
  {
    "hook_event_name": "PostToolUse",
    "tool_name": "Edit"|"Write",
    "tool_input": {"file_path": "...", "old_string": "...", "new_string": "..."},
    "tool_response": {"filePath": "...", "success": true},
    "tool_use_id": "toolu_..."
  }

Appends a structured entry to .muninn/edits_log.jsonl. Used for:
- Detecting drift (which files Claude touches the most)
- Counting lines added/deleted per session for dashboards
- Triggering external linters / static analysis after each edit (in a
  follow-up automation)
- Compliance: who modified what, when

Cap at 10000 entries (drop oldest first).

Design rules:
- Never raise. Exit 0 always.
- Atomic write via tempfile.
- Track tool_name, file_path, old/new size, ts. Don't store the actual
  content (would explode the log file).

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import sys
import tempfile
from datetime import datetime
from pathlib import Path

# --- PIPELINE_TRACE block (removable, see docs/PIPELINE_TRACE_REMOVAL.md) ---  # PIPELINE_TRACE
try:  # PIPELINE_TRACE
    _pt_dir = str(Path(__file__).resolve().parent.parent.parent / "engine" / "core")  # PIPELINE_TRACE
    if _pt_dir not in sys.path: sys.path.insert(0, _pt_dir)  # PIPELINE_TRACE
    from pipeline_trace import log_event  # PIPELINE_TRACE
except Exception:  # PIPELINE_TRACE
    def log_event(*a, **kw): pass  # PIPELINE_TRACE
# --- end PIPELINE_TRACE block ---  # PIPELINE_TRACE


def _log_hook_error(context: str, exc: BaseException) -> None:
    """Append a swallowed exception to ~/.muninn/hook_errors.log.

    F5 (2026-05-10): delegates to engine/core/_hook_logger which
    rotates the file (1 MB max, 3 backups) and falls back to stderr if
    the file is unwritable so the audit trail is never silently lost.
    """
    try:
        engine_core = str(Path(__file__).resolve().parent.parent.parent
                          / "engine" / "core")
        if engine_core not in sys.path:
            sys.path.insert(0, engine_core)
        from _hook_logger import log_hook_event
        log_hook_event("post_tool_use_edit_log", context, exc)
    except Exception:
        # Last-resort fallback: write directly to stderr; hooks must exit 0.
        try:
            sys.stderr.write(
                f"[MUNINN HOOK LOG fallback] {datetime.now().isoformat()} "
                f"[post_tool_use_edit_log:{context}] {type(exc).__name__}: {exc}\n"
            )
            sys.stderr.flush()
        except Exception:
            pass


MAX_ENTRIES = 10000


def _load_existing(log_path: Path) -> list:
    if not log_path.exists():
        return []
    try:
        out = []
        for line in log_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
        return out
    except OSError:
        return []


def _atomic_write_jsonl(log_path: Path, entries: list) -> None:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(
        dir=str(log_path.parent), suffix=".tmp", prefix=".edits-"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            for entry in entries:
                f.write(json.dumps(entry, ensure_ascii=False) + "\n")
        os.replace(tmp, str(log_path))
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def append_edit_log(payload: dict, repo_path: Path) -> bool:
    if not isinstance(payload, dict):
        return False

    tool_name = payload.get("tool_name", "")
    if tool_name not in ("Edit", "Write"):
        return False

    tool_input = payload.get("tool_input", {}) or {}
    if not isinstance(tool_input, dict):
        return False

    file_path = tool_input.get("file_path", "")
    if not file_path:
        return False

    if tool_name == "Write":
        new_content = tool_input.get("content", "") or ""
        old_size = 0
        new_size = len(new_content)
    else:  # Edit
        old_string = tool_input.get("old_string", "") or ""
        new_string = tool_input.get("new_string", "") or ""
        old_size = len(old_string)
        new_size = len(new_string)

    entry = {
        "ts": datetime.now().isoformat(timespec="seconds"),
        "tool": tool_name,
        "file_path": file_path,
        "old_size": old_size,
        "new_size": new_size,
        "delta": new_size - old_size,
        "session_id": payload.get("session_id", ""),
        "tool_use_id": payload.get("tool_use_id", ""),
    }

    log_path = Path(repo_path) / ".muninn" / "edits_log.jsonl"
    existing = _load_existing(log_path)
    existing.append(entry)

    if len(existing) > MAX_ENTRIES:
        existing = existing[-MAX_ENTRIES:]

    _atomic_write_jsonl(log_path, existing)
    return True


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
    except UnicodeDecodeError as e:
        _log_hook_error("stdin_decode", e)
        sys.exit(0)
    except Exception as e:
        _log_hook_error("stdin_read", e)
        sys.exit(0)
    if not raw.strip():
        sys.exit(0)
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as e:
        _log_hook_error("stdin_parse", e)
        sys.exit(0)
    except Exception as e:
        _log_hook_error("stdin_unexpected", e)
        sys.exit(0)

    # Audit 2026-04-10: type-check before .get() to never crash on bad input
    if not isinstance(payload, dict):
        sys.exit(0)

    repo_path = payload.get("cwd") or os.getcwd()
    log_event("pipeline.hook.edit_log.begin", {"tool": payload.get("tool_name", "")})  # PIPELINE_TRACE

    try:
        _pt_logged = append_edit_log(payload, Path(repo_path))  # PIPELINE_TRACE
        log_event("pipeline.hook.edit_log.logged", {"appended": bool(_pt_logged)})  # PIPELINE_TRACE
    except Exception as e:
        _log_hook_error("append_edit_log", e)

    sys.exit(0)


if __name__ == "__main__":
    main()
