#!/usr/bin/env python3
"""PostToolUseFailure hook — auto-feed errors.json from real-time tool failures.

Reads PostToolUseFailure JSON payload from stdin (Claude Code spec).
Appends a new entry to .muninn/errors.json in P18 schema:
  {"error": "<tool> | <summary>", "fix": "", "date": "YYYY-MM-DD"}

Design:
- NEVER raise (always exit 0). Hook failure must not block Claude.
- NEVER write to stdout (PostToolUseFailure is non-blocking, would be lost).
- Atomic write via tempfile + os.replace.
- Dedup: skip if last entry has identical (error, date).
- Cap errors.json at 500 entries (drop oldest first).

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import sys
import tempfile
from datetime import datetime
from pathlib import Path

MAX_ENTRIES = 500


def _safe_summary(tool_name, error, max_len=200):
    if not error:
        error = "(no error message)"
    first = error.splitlines()[0] if error else ""
    summary = f"{tool_name} | {first}"
    if len(summary) > max_len:
        summary = summary[: max_len - 3] + "..."
    return summary


def _load_existing(errors_path):
    if not errors_path.exists():
        return []
    try:
        data = json.loads(errors_path.read_text(encoding="utf-8"))
        if isinstance(data, list):
            return data
        return []
    except Exception:
        return []


def _atomic_write(errors_path, data):
    errors_path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(
        dir=str(errors_path.parent), suffix=".tmp", prefix=".errors-"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        os.replace(tmp, str(errors_path))
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def feed_errors_json(payload, repo_path):
    if not isinstance(payload, dict):
        return False
    tool_name = payload.get("tool_name", "")
    error_msg = payload.get("error", "")
    if not tool_name and not error_msg:
        return False

    errors_path = Path(repo_path) / ".muninn" / "errors.json"
    existing = _load_existing(errors_path)

    summary = _safe_summary(tool_name, error_msg)
    today = datetime.now().strftime("%Y-%m-%d")
    entry = {"error": summary, "fix": "", "date": today}

    if existing and isinstance(existing[-1], dict):
        last = existing[-1]
        if last.get("error") == summary and last.get("date") == today:
            return False

    existing.append(entry)

    if len(existing) > MAX_ENTRIES:
        existing = existing[-MAX_ENTRIES:]

    _atomic_write(errors_path, existing)
    return True


def _log_failure(context, exc):
    """2026-05-13 drift-fix : restore audit trail (F5 regression)."""
    try:
        engine_core = str(Path(__file__).resolve().parent.parent.parent
                          / "engine" / "core")
        if engine_core not in sys.path:
            sys.path.insert(0, engine_core)
        from _hook_logger import log_hook_event
        log_hook_event("post_tool_failure_hook", context, exc)
    except Exception:
        try:
            sys.stderr.write(
                f"[MUNINN HOOK LOG fallback] [post_tool_failure_hook:"
                f"{context}] {type(exc).__name__}: {exc}\n"
            )
            sys.stderr.flush()
        except Exception:
            pass  # true last resort — nowhere to write if stderr fails


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
    except (UnicodeDecodeError, OSError) as e:
        _log_failure("stdin_decode", e)
        sys.exit(0)
    try:
        payload = json.loads(raw)
    except (json.JSONDecodeError, ValueError) as e:
        _log_failure("stdin_parse", e)
        sys.exit(0)
    except Exception as e:
        _log_failure("stdin_unexpected", e)
        sys.exit(0)

    # Audit 2026-04-10: type-check before .get() to never crash on bad input
    if not isinstance(payload, dict):
        sys.exit(0)

    repo_path = payload.get("cwd") or os.getcwd()

    try:
        feed_errors_json(payload, Path(repo_path))
    except Exception as e:
        _log_failure("feed_errors_json", e)

    sys.exit(0)


if __name__ == "__main__":
    main()
