#!/usr/bin/env python3
"""PostToolUse Edit/Write hook — log every successful file modification.

Reads PostToolUse JSON payload from stdin (Claude Code spec):
  {
    "hook_event_name": "PostToolUse",
    "tool_name": "Edit"|"Write",
    "tool_input": {"file_path": "...", "old_string": "...", "new_string": "..."},
    "tool_response": {"filePath": "...", "success": true},
    "tool_use_id": "toolu_..."
  }

Appends a structured entry to .muninn/edits_log.jsonl. Used for:
- Detecting drift (which files Claude touches the most)
- Counting lines added/deleted per session for dashboards
- Triggering external linters / static analysis after each edit (in a
  follow-up automation)
- Compliance: who modified what, when

Cap at 10000 entries (drop oldest first).

Design rules:
- Never raise. Exit 0 always.
- Atomic write via tempfile.
- Track tool_name, file_path, old/new size, ts. Don't store the actual
  content (would explode the log file).

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import sys
import tempfile
from datetime import datetime
from pathlib import Path

MAX_ENTRIES = 10000


def _load_existing(log_path: Path) -> list:
    if not log_path.exists():
        return []
    try:
        out = []
        for line in log_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                out.append(json.loads(line))
            except json.JSONDecodeError:
                continue
        return out
    except OSError:
        return []


def _atomic_write_jsonl(log_path: Path, entries: list) -> None:
    log_path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(
        dir=str(log_path.parent), suffix=".tmp", prefix=".edits-"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            for entry in entries:
                f.write(json.dumps(entry, ensure_ascii=False) + "\n")
        os.replace(tmp, str(log_path))
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def append_edit_log(payload: dict, repo_path: Path) -> bool:
    if not isinstance(payload, dict):
        return False

    tool_name = payload.get("tool_name", "")
    if tool_name not in ("Edit", "Write"):
        return False

    tool_input = payload.get("tool_input", {}) or {}
    if not isinstance(tool_input, dict):
        return False

    file_path = tool_input.get("file_path", "")
    if not file_path:
        return False

    if tool_name == "Write":
        new_content = tool_input.get("content", "") or ""
        old_size = 0
        new_size = len(new_content)
    else:  # Edit
        old_string = tool_input.get("old_string", "") or ""
        new_string = tool_input.get("new_string", "") or ""
        old_size = len(old_string)
        new_size = len(new_string)

    entry = {
        "ts": datetime.now().isoformat(timespec="seconds"),
        "tool": tool_name,
        "file_path": file_path,
        "old_size": old_size,
        "new_size": new_size,
        "delta": new_size - old_size,
        "session_id": payload.get("session_id", ""),
        "tool_use_id": payload.get("tool_use_id", ""),
    }

    log_path = Path(repo_path) / ".muninn" / "edits_log.jsonl"
    existing = _load_existing(log_path)
    existing.append(entry)

    if len(existing) > MAX_ENTRIES:
        existing = existing[-MAX_ENTRIES:]

    _atomic_write_jsonl(log_path, existing)
    return True


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
        payload = json.loads(raw)
    except Exception:
        sys.exit(0)

    repo_path = payload.get("cwd") or os.getcwd()

    try:
        append_edit_log(payload, Path(repo_path))
    except Exception:
        pass

    sys.exit(0)


if __name__ == "__main__":
    main()
