#!/usr/bin/env python3
"""PreToolUse Bash hook — block commands that would expose secrets.

Reads PreToolUse JSON payload from stdin (Claude Code spec).

If the command would echo / print / cat a secret-like environment variable
or file, exit code 2 (block) with stderr feedback. Otherwise exit 0.

This hook is the enforcement layer for CLAUDE.md RULE 3:
"Never display secrets".

Design rules:
- Block obvious patterns: echo $TOKEN, cat .env, env | grep KEY, etc.
- Allow safe alternatives: [ -n "$VAR" ] && echo set, echo ${#VAR}, etc.
- Conservative: false negatives (let one through) > false positives
  (frustrate Sky on legit commands).

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import re
import sys


# Var name patterns that indicate secrets
SECRET_VAR_PATTERN = re.compile(
    r'(?:TOKEN|SECRET|KEY|PASSWORD|PASSWD|CREDENTIAL|PRIVATE|API_KEY|'
    r'ANTHROPIC|OPENAI|AWS|GITHUB|GITLAB|NPM_TOKEN|PYPI)',
    re.IGNORECASE,
)

# Commands that DISPLAY content (vs commands that just check existence)
# We block when these are combined with a secret-like target
DISPLAY_COMMANDS = re.compile(
    r'\b(?:echo|cat|printenv|env|less|more|head|tail|print|printf|tee)\b',
    re.IGNORECASE,
)

# Safe patterns that should NOT trigger the block
# (these are checks of existence/length without revealing content)
SAFE_PATTERNS = [
    r'echo\s+\$\{#\w+\}',      # echo ${#VAR} = length
    r'\[\s*-n\s+["\']?\$',     # [ -n "$VAR" ]
    r'\[\s*-z\s+["\']?\$',     # [ -z "$VAR" ]
    r'echo\s+["\']?(?:set|not\s+set|undefined|exists)["\']?',
]
_SAFE_COMPILED = [re.compile(p, re.IGNORECASE) for p in SAFE_PATTERNS]


def is_safe_check(command: str) -> bool:
    """Return True if this looks like a length/existence check, not a value display."""
    return any(p.search(command) for p in _SAFE_COMPILED)


def check_secret_exposure(command: str) -> tuple[bool, str]:
    """Return (would_expose_secret, reason).

    Conservative: only block if both DISPLAY_COMMAND and SECRET_VAR are present.
    """
    if not command:
        return False, ""

    if is_safe_check(command):
        return False, ""

    # 1. Direct echo of secret-named variable
    # echo $GITHUB_TOKEN, echo $AWS_SECRET_KEY, etc.
    m = re.search(r'\$(?:\{|\b)([A-Z_]+(?:TOKEN|SECRET|KEY|PASSWORD|CREDENTIAL))', command, re.IGNORECASE)
    if m and DISPLAY_COMMANDS.search(command):
        return True, f"display of $-var matching secret pattern: {m.group(1)}"

    # 2. cat .env / cat ~/.aws/credentials etc.
    secret_files = re.search(
        r'\b(?:cat|less|more|head|tail|tee)\s+[^\s]*'
        r'(?:\.env\b|credentials\b|\.netrc\b|id_rsa\b|id_ed25519\b|\.pgpass\b|\.npmrc\b)',
        command,
        re.IGNORECASE,
    )
    if secret_files:
        return True, f"display of secret file: {secret_files.group(0)[:60]}"

    # 3. env | grep <secret pattern>
    if re.search(r'\benv\b[^|]*\|\s*grep', command, re.IGNORECASE):
        if SECRET_VAR_PATTERN.search(command):
            return True, "env | grep filtering for secret-named var"

    # 4. printenv with secret name
    if re.search(r'\bprintenv\s+\w*(?:TOKEN|SECRET|KEY|PASSWORD)', command, re.IGNORECASE):
        return True, "printenv on secret-named var"

    return False, ""


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
        payload = json.loads(raw)
    except Exception:
        sys.exit(0)

    if not isinstance(payload, dict):
        sys.exit(0)
    if payload.get("tool_name") != "Bash":
        sys.exit(0)

    tool_input = payload.get("tool_input", {})
    command = tool_input.get("command", "") if isinstance(tool_input, dict) else ""
    if not isinstance(command, str):
        sys.exit(0)

    would_expose, reason = check_secret_exposure(command)
    if not would_expose:
        sys.exit(0)

    msg = (
        f"[MUNINN PRE-TOOL HOOK] Blocked Bash command that would expose a secret.\n"
        f"Reason: {reason}\n"
        f"Command: {command[:200]}\n\n"
        f"This is enforced by CLAUDE.md RULE 3 (Never display secrets).\n"
        f"Safe alternatives:\n"
        f"  - Check existence: [ -n \"$VAR\" ] && echo 'set' || echo 'unset'\n"
        f"  - Check length: echo \"length: ${{#VAR}}\"\n"
        f"  - Test it works: curl -s -H \"Authorization: Bearer $VAR\" <api> | jq .login\n"
        f"Do not retry with the same command."
    )
    print(msg, file=sys.stderr)
    sys.exit(2)


if __name__ == "__main__":
    main()
