#!/usr/bin/env python3
"""PreToolUse Bash hook — block destructive operations without confirmation.

Reads PreToolUse JSON payload from stdin (Claude Code spec):
  {
    "hook_event_name": "PreToolUse",
    "tool_name": "Bash",
    "tool_input": { "command": "...", ... },
    "tool_use_id": "toolu_...",
    "permission_mode": "default"
  }

If the command matches any DESTRUCTIVE pattern, exit code 2 (block) with
a stderr message that Claude sees as feedback. Otherwise exit 0 (allow).

This hook is the enforcement layer for CLAUDE.md RULE 2:
"Confirm before destructive actions".

Design rules:
- Never raise (always exit 0 or 2). Crashes from this hook would block all
  Bash commands silently — much worse than letting one through.
- Conservative pattern matching. Better to let one ambiguous command through
  than to block legit work and frustrate Sky.
- Provide a CLEAR stderr message so Claude understands WHY it was blocked.

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

# --- PIPELINE_TRACE block (removable, see docs/PIPELINE_TRACE_REMOVAL.md) ---  # PIPELINE_TRACE
try:  # PIPELINE_TRACE
    _pt_dir = str(Path(__file__).resolve().parent.parent.parent / "engine" / "core")  # PIPELINE_TRACE
    if _pt_dir not in sys.path: sys.path.insert(0, _pt_dir)  # PIPELINE_TRACE
    from pipeline_trace import log_event  # PIPELINE_TRACE
except Exception:  # PIPELINE_TRACE
    def log_event(*a, **kw): pass  # PIPELINE_TRACE
# --- end PIPELINE_TRACE block ---  # PIPELINE_TRACE


def _log_hook_error(context: str, exc: BaseException) -> None:
    """Append a swallowed exception to ~/.muninn/hook_errors.log.

    F5 (2026-05-10): delegates to engine/core/_hook_logger which
    rotates the file (1 MB max, 3 backups) and falls back to stderr if
    the file is unwritable so the audit trail is never silently lost.
    """
    try:
        engine_core = str(Path(__file__).resolve().parent.parent.parent
                          / "engine" / "core")
        if engine_core not in sys.path:
            sys.path.insert(0, engine_core)
        from _hook_logger import log_hook_event
        log_hook_event("pre_tool_use_bash_destructive", context, exc)
    except Exception:
        # Last-resort fallback: write directly to stderr; hooks must exit 0.
        try:
            sys.stderr.write(
                f"[MUNINN HOOK LOG fallback] {datetime.now().isoformat()} "
                f"[pre_tool_use_bash_destructive:{context}] {type(exc).__name__}: {exc}\n"
            )
            sys.stderr.flush()
        except Exception:
            pass


# Patterns that ALWAYS need confirmation, even if Sky asked once
# Audit 2026-04-10: added foo/* glob, combined short flags (-fu), eval-wrapped
DESTRUCTIVE_PATTERNS = [
    # Force-push (long, short, with-lease)
    (r'\bgit\s+push\b[^|;&]*--force\b', "git push --force"),
    (r'\bgit\s+push\b[^|;&]*--force-with-lease\b', "git push --force-with-lease"),
    # Short flags: -f alone OR combined like -fu, -uf, -fuv
    (r'\bgit\s+push\b[^|;&]*\s-[a-z]*f[a-z]*\b', "git push -f (short or combined)"),

    # Hard reset
    (r'\bgit\s+reset\b[^|;&]*--hard\b', "git reset --hard"),

    # Branch deletion
    (r'\bgit\s+branch\b[^|;&]*-D\b', "git branch -D (force delete)"),
    (r'\bgit\s+push\b[^|;&]*--delete\b', "git push --delete"),

    # rm -rf at dangerous locations
    (r'\brm\s+-rf?\s+/(?:\s|$)', "rm -rf /"),
    (r'\brm\s+-rf?\s+~/?(?:\s|$)', "rm -rf ~"),
    (r'\brm\s+-rf?\s+\$HOME', "rm -rf $HOME"),
    (r'\brm\s+-rf?\s+\.\s*$', "rm -rf . (current dir)"),
    (r'\brm\s+-rf?\s+\.\s', "rm -rf . (current dir)"),
    # rm -rf glob patterns: *, *.ext, foo/*, ../foo, etc.
    (r'\brm\s+-rf?\s+[^\s|;&]*\*', "rm -rf <glob>"),
    (r'\brm\s+-rf?\s+\.\.', "rm -rf ../ (parent)"),

    # SQL destructive
    (r'\bDROP\s+(?:TABLE|DATABASE|SCHEMA|INDEX)\b', "DROP TABLE/DATABASE"),
    (r'\bTRUNCATE\s+TABLE\b', "TRUNCATE TABLE"),
    (r'\bDELETE\s+FROM\s+\w+\s*(?:;|$)', "DELETE FROM (no WHERE)"),

    # Disk wipe
    (r'\bdd\s+if=/dev/(?:zero|random|urandom)\s+of=/dev/', "dd to /dev/"),
    (r'\bmkfs\.', "mkfs (filesystem creation)"),

    # System
    (r'\b(?:shutdown|reboot|halt)\s+', "shutdown/reboot/halt"),

    # Skip safety
    (r'--no-verify\b', "--no-verify (skip git hooks)"),
    (r'--dangerously-skip-permissions\b', "--dangerously-skip-permissions"),

    # Eval/exec wrapping (executes its argument as shell command)
    # We block any eval/exec/sh -c that contains another destructive marker
    (r'\b(?:eval|exec|sh\s+-c|bash\s+-c)\b[^"\']*["\'][^"\']*(?:rm\s+-rf|--force|--no-verify|DROP\s+TABLE|TRUNCATE)', "eval/exec wrapping destructive"),
]

# Compile once
_COMPILED = [(re.compile(p, re.IGNORECASE), label) for p, label in DESTRUCTIVE_PATTERNS]


def check_destructive(command: str) -> tuple[bool, str]:
    """Return (is_destructive, matched_pattern_label)."""
    if not command:
        return False, ""
    for pat, label in _COMPILED:
        if pat.search(command):
            return True, label
    return False, ""


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
    except UnicodeDecodeError as e:
        _log_hook_error("stdin_decode", e)
        sys.exit(0)
    except Exception as e:
        _log_hook_error("stdin_read", e)
        sys.exit(0)
    if not raw.strip():
        sys.exit(0)
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as e:
        _log_hook_error("stdin_parse", e)
        sys.exit(0)
    except Exception as e:
        _log_hook_error("stdin_unexpected", e)
        sys.exit(0)

    if not isinstance(payload, dict):
        sys.exit(0)

    if payload.get("tool_name") != "Bash":
        sys.exit(0)

    tool_input = payload.get("tool_input", {})
    if not isinstance(tool_input, dict):
        sys.exit(0)

    command = tool_input.get("command", "")
    if not isinstance(command, str):
        sys.exit(0)

    log_event("pipeline.hook.pre_bash_destructive.begin", {"cmd_len": len(command), "cmd_head": command[:60]})  # PIPELINE_TRACE

    is_destructive, label = check_destructive(command)
    if not is_destructive:
        log_event("pipeline.hook.pre_bash_destructive.allowed", {})  # PIPELINE_TRACE
        sys.exit(0)

    log_event("pipeline.hook.pre_bash_destructive.blocked", {"label": label, "cmd_head": command[:120]}, level="warn")  # PIPELINE_TRACE
    # BLOCK: print to stderr (Claude sees this as feedback) and exit 2
    msg = (
        f"[MUNINN PRE-TOOL HOOK] Blocked destructive Bash command.\n"
        f"Pattern matched: {label}\n"
        f"Command: {command[:200]}\n\n"
        f"This is enforced by CLAUDE.md RULE 2 (Confirm before destructive\n"
        f"actions). Sky must explicitly confirm BEFORE you run this command.\n"
        f"Ask Sky in chat: 'This will <effect>. Confirm?' and wait for the\n"
        f"answer. Do not retry the same command."
    )
    print(msg, file=sys.stderr)
    sys.exit(2)


if __name__ == "__main__":
    main()
