#!/usr/bin/env python3
"""PreToolUse Bash hook — block destructive operations without confirmation.

Reads PreToolUse JSON payload from stdin (Claude Code spec):
  {
    "hook_event_name": "PreToolUse",
    "tool_name": "Bash",
    "tool_input": { "command": "...", ... },
    "tool_use_id": "toolu_...",
    "permission_mode": "default"
  }

If the command matches any DESTRUCTIVE pattern, exit code 2 (block) with
a stderr message that Claude sees as feedback. Otherwise exit 0 (allow).

This hook is the enforcement layer for CLAUDE.md RULE 2:
"Confirm before destructive actions".

Design rules:
- Never raise (always exit 0 or 2). Crashes from this hook would block all
  Bash commands silently — much worse than letting one through.
- Conservative pattern matching. Better to let one ambiguous command through
  than to block legit work and frustrate Sky.
- Provide a CLEAR stderr message so Claude understands WHY it was blocked.

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import re
import sys


# Patterns that ALWAYS need confirmation, even if Sky asked once
DESTRUCTIVE_PATTERNS = [
    # Force-push
    (r'\bgit\s+push\b[^|;&]*--force\b', "git push --force"),
    (r'\bgit\s+push\b[^|;&]*-f\b', "git push -f"),
    (r'\bgit\s+push\b[^|;&]*--force-with-lease\b', "git push --force-with-lease"),

    # Hard reset
    (r'\bgit\s+reset\b[^|;&]*--hard\b', "git reset --hard"),

    # Branch deletion
    (r'\bgit\s+branch\b[^|;&]*-D\b', "git branch -D (force delete)"),
    (r'\bgit\s+push\b[^|;&]*--delete\b', "git push --delete"),

    # rm -rf at dangerous locations
    (r'\brm\s+-rf?\s+/(?:\s|$)', "rm -rf /"),
    (r'\brm\s+-rf?\s+~/?(?:\s|$)', "rm -rf ~"),
    (r'\brm\s+-rf?\s+\$HOME', "rm -rf $HOME"),
    (r'\brm\s+-rf?\s+\.', "rm -rf . (current dir)"),
    (r'\brm\s+-rf?\s+\*', "rm -rf *"),

    # SQL destructive
    (r'\bDROP\s+(?:TABLE|DATABASE|SCHEMA|INDEX)\b', "DROP TABLE/DATABASE"),
    (r'\bTRUNCATE\s+TABLE\b', "TRUNCATE TABLE"),
    (r'\bDELETE\s+FROM\s+\w+\s*(?:;|$)', "DELETE FROM (no WHERE)"),

    # Disk wipe
    (r'\bdd\s+if=/dev/(?:zero|random|urandom)\s+of=/dev/', "dd to /dev/"),
    (r'\bmkfs\.', "mkfs (filesystem creation)"),

    # System
    (r'\b(?:shutdown|reboot|halt)\s+', "shutdown/reboot/halt"),

    # Skip safety
    (r'--no-verify\b', "--no-verify (skip git hooks)"),
    (r'--dangerously-skip-permissions\b', "--dangerously-skip-permissions"),
]

# Compile once
_COMPILED = [(re.compile(p, re.IGNORECASE), label) for p, label in DESTRUCTIVE_PATTERNS]


def check_destructive(command: str) -> tuple[bool, str]:
    """Return (is_destructive, matched_pattern_label)."""
    if not command:
        return False, ""
    for pat, label in _COMPILED:
        if pat.search(command):
            return True, label
    return False, ""


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
        payload = json.loads(raw)
    except Exception:
        sys.exit(0)

    if not isinstance(payload, dict):
        sys.exit(0)

    if payload.get("tool_name") != "Bash":
        sys.exit(0)

    tool_input = payload.get("tool_input", {})
    if not isinstance(tool_input, dict):
        sys.exit(0)

    command = tool_input.get("command", "")
    if not isinstance(command, str):
        sys.exit(0)

    is_destructive, label = check_destructive(command)
    if not is_destructive:
        sys.exit(0)

    # BLOCK: print to stderr (Claude sees this as feedback) and exit 2
    msg = (
        f"[MUNINN PRE-TOOL HOOK] Blocked destructive Bash command.\n"
        f"Pattern matched: {label}\n"
        f"Command: {command[:200]}\n\n"
        f"This is enforced by CLAUDE.md RULE 2 (Confirm before destructive\n"
        f"actions). Sky must explicitly confirm BEFORE you run this command.\n"
        f"Ask Sky in chat: 'This will <effect>. Confirm?' and wait for the\n"
        f"answer. Do not retry the same command."
    )
    print(msg, file=sys.stderr)
    sys.exit(2)


if __name__ == "__main__":
    main()
