#!/usr/bin/env python3
"""PreToolUse Edit/Write hook — block hardcoded paths in engine code.

Reads PreToolUse JSON payload from stdin (Claude Code spec).

If the file being modified is in engine/core/ or muninn/ AND the new
content introduces a hardcoded path containing 'MUNINN-' or
'C:/Users/' inside a function body (not just a comment), exit code 2
(block) with stderr feedback. Otherwise exit 0.

This hook is the enforcement layer for CLAUDE.md RULE 1:
"Universal code, never repo-hardcoded".

Design rules:
- Only check writes to engine code (engine/core/*.py, muninn/*.py).
- Other files (tests, docs, scripts) are exempt — hardcodes there
  are usually intentional (test fixtures, example commands).
- Distinguish code lines from comments: a comment containing the path
  as a counter-example is allowed.
- Conservative: if unsure, allow.

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path

# --- PIPELINE_TRACE block (removable, see docs/PIPELINE_TRACE_REMOVAL.md) ---  # PIPELINE_TRACE
try:  # PIPELINE_TRACE
    _pt_dir = str(Path(__file__).resolve().parent.parent.parent / "engine" / "core")  # PIPELINE_TRACE
    if _pt_dir not in sys.path: sys.path.insert(0, _pt_dir)  # PIPELINE_TRACE
    from pipeline_trace import log_event  # PIPELINE_TRACE
except Exception:  # PIPELINE_TRACE
    def log_event(*a, **kw): pass  # PIPELINE_TRACE
# --- end PIPELINE_TRACE block ---  # PIPELINE_TRACE


def _log_hook_error(context: str, exc: BaseException) -> None:
    """Append a swallowed exception to ~/.muninn/hook_errors.log.

    F5 (2026-05-10): delegates to engine/core/_hook_logger which
    rotates the file (1 MB max, 3 backups) and falls back to stderr if
    the file is unwritable so the audit trail is never silently lost.
    """
    try:
        engine_core = str(Path(__file__).resolve().parent.parent.parent
                          / "engine" / "core")
        if engine_core not in sys.path:
            sys.path.insert(0, engine_core)
        from _hook_logger import log_hook_event
        log_hook_event("pre_tool_use_edit_hardcode", context, exc)
    except Exception:
        # Last-resort fallback: write directly to stderr; hooks must exit 0.
        try:
            sys.stderr.write(
                f"[MUNINN HOOK LOG fallback] {datetime.now().isoformat()} "
                f"[pre_tool_use_edit_hardcode:{context}] {type(exc).__name__}: {exc}\n"
            )
            sys.stderr.flush()
        except Exception:
            pass


# Paths under these dirs are subject to the rule
PROTECTED_DIRS = [
    "engine/core/",
    "engine\\core\\",
    "muninn/",
    "muninn\\",
]

# Patterns that look like a hardcoded MUNINN- path
HARDCODE_PATTERNS = [
    re.compile(r'["\']?[A-Z]:[/\\]Users[/\\][^"\'\s]*MUNINN-'),
    re.compile(r'["\']?/Users/[^"\'\s]*MUNINN-'),
    re.compile(r'["\']?/home/[^"\'\s]*MUNINN-'),
]


def is_protected_path(file_path: str) -> bool:
    """Check if the file lives under a protected directory."""
    if not file_path:
        return False
    norm = file_path.replace("\\", "/").lower()
    return any(d.replace("\\", "/").lower() in norm for d in PROTECTED_DIRS)


def find_hardcode_in_content(content: str) -> tuple[bool, str]:
    """Scan content for hardcoded paths in non-comment lines.

    Returns (found, sample_line).
    """
    if not content:
        return False, ""

    for line in content.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        # Skip pure comment lines (Python/JS/etc)
        if stripped.startswith("#") or stripped.startswith("//"):
            continue
        # Skip docstrings (rough heuristic — line is inside or starts with """)
        if stripped.startswith('"""') or stripped.startswith("'''"):
            continue

        # Strip inline comment
        code_part = line
        for cmt in ["#", "//"]:
            idx = code_part.find(cmt)
            if idx >= 0:
                # Check if # is inside a string (very rough)
                before = code_part[:idx]
                if before.count('"') % 2 == 0 and before.count("'") % 2 == 0:
                    code_part = code_part[:idx]

        for pat in HARDCODE_PATTERNS:
            if pat.search(code_part):
                return True, line.strip()[:200]
    return False, ""


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
    except UnicodeDecodeError as e:
        _log_hook_error("stdin_decode", e)
        sys.exit(0)
    except Exception as e:
        _log_hook_error("stdin_read", e)
        sys.exit(0)
    if not raw.strip():
        sys.exit(0)
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as e:
        _log_hook_error("stdin_parse", e)
        sys.exit(0)
    except Exception as e:
        _log_hook_error("stdin_unexpected", e)
        sys.exit(0)

    if not isinstance(payload, dict):
        sys.exit(0)

    tool_name = payload.get("tool_name")
    if tool_name not in ("Edit", "Write"):
        sys.exit(0)

    tool_input = payload.get("tool_input", {})
    if not isinstance(tool_input, dict):
        sys.exit(0)

    file_path = tool_input.get("file_path", "")
    if not isinstance(file_path, str):
        sys.exit(0)

    if not is_protected_path(file_path):
        sys.exit(0)

    # Get the new content (Write) or new_string (Edit)
    if tool_name == "Write":
        content = tool_input.get("content", "")
    else:  # Edit
        content = tool_input.get("new_string", "")

    if not isinstance(content, str):
        sys.exit(0)

    log_event("pipeline.hook.pre_edit_hardcode.begin", {"tool": tool_name, "file_path": file_path[:120], "content_len": len(content)})  # PIPELINE_TRACE

    found, sample = find_hardcode_in_content(content)
    if not found:
        log_event("pipeline.hook.pre_edit_hardcode.allowed", {})  # PIPELINE_TRACE
        sys.exit(0)

    log_event("pipeline.hook.pre_edit_hardcode.blocked", {"file_path": file_path[:120], "sample": sample[:120]}, level="warn")  # PIPELINE_TRACE
    msg = (
        f"[MUNINN PRE-TOOL HOOK] Blocked {tool_name} introducing hardcoded path.\n"
        f"File: {file_path}\n"
        f"Offending line: {sample}\n\n"
        f"This is enforced by CLAUDE.md RULE 1 (Universal code, never repo-hardcoded).\n"
        f"engine/core/ and muninn/ must NOT contain absolute paths to MUNINN-.\n"
        f"Use one of:\n"
        f"  - _REPO_PATH module global (already managed by Muninn)\n"
        f"  - os.environ.get('MUNINN_REPO', ...)\n"
        f"  - Path(__file__).resolve().parent (relative to module)\n"
        f"  - Function argument passed by caller\n"
        f"Do not retry. Refactor to parameterize the path."
    )
    print(msg, file=sys.stderr)
    sys.exit(2)


if __name__ == "__main__":
    main()
