#!/usr/bin/env python3
"""PreToolUse Edit/Write hook — block hardcoded paths in engine code.

Reads PreToolUse JSON payload from stdin (Claude Code spec).

If the file being modified is in engine/core/ or muninn/ AND the new
content introduces a hardcoded path containing 'MUNINN-' or
'C:/Users/' inside a function body (not just a comment), exit code 2
(block) with stderr feedback. Otherwise exit 0.

This hook is the enforcement layer for CLAUDE.md RULE 1:
"Universal code, never repo-hardcoded".

Design rules:
- Only check writes to engine code (engine/core/*.py, muninn/*.py).
- Other files (tests, docs, scripts) are exempt — hardcodes there
  are usually intentional (test fixtures, example commands).
- Distinguish code lines from comments: a comment containing the path
  as a counter-example is allowed.
- Conservative: if unsure, allow.

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import re
import sys
from pathlib import Path


# Paths under these dirs are subject to the rule
PROTECTED_DIRS = [
    "engine/core/",
    "engine\\core\\",
    "muninn/",
    "muninn\\",
]

# Patterns that look like a hardcoded MUNINN- path
HARDCODE_PATTERNS = [
    re.compile(r'["\']?[A-Z]:[/\\]Users[/\\][^"\'\s]*MUNINN-'),
    re.compile(r'["\']?/Users/[^"\'\s]*MUNINN-'),
    re.compile(r'["\']?/home/[^"\'\s]*MUNINN-'),
]


def is_protected_path(file_path: str) -> bool:
    """Check if the file lives under a protected directory."""
    if not file_path:
        return False
    norm = file_path.replace("\\", "/").lower()
    return any(d.replace("\\", "/").lower() in norm for d in PROTECTED_DIRS)


def find_hardcode_in_content(content: str) -> tuple[bool, str]:
    """Scan content for hardcoded paths in non-comment lines.

    Returns (found, sample_line).
    """
    if not content:
        return False, ""

    for line in content.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        # Skip pure comment lines (Python/JS/etc)
        if stripped.startswith("#") or stripped.startswith("//"):
            continue
        # Skip docstrings (rough heuristic — line is inside or starts with """)
        if stripped.startswith('"""') or stripped.startswith("'''"):
            continue

        # Strip inline comment
        code_part = line
        for cmt in ["#", "//"]:
            idx = code_part.find(cmt)
            if idx >= 0:
                # Check if # is inside a string (very rough)
                before = code_part[:idx]
                if before.count('"') % 2 == 0 and before.count("'") % 2 == 0:
                    code_part = code_part[:idx]

        for pat in HARDCODE_PATTERNS:
            if pat.search(code_part):
                return True, line.strip()[:200]
    return False, ""


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
        payload = json.loads(raw)
    except Exception:
        sys.exit(0)

    if not isinstance(payload, dict):
        sys.exit(0)

    tool_name = payload.get("tool_name")
    if tool_name not in ("Edit", "Write"):
        sys.exit(0)

    tool_input = payload.get("tool_input", {})
    if not isinstance(tool_input, dict):
        sys.exit(0)

    file_path = tool_input.get("file_path", "")
    if not isinstance(file_path, str):
        sys.exit(0)

    if not is_protected_path(file_path):
        sys.exit(0)

    # Get the new content (Write) or new_string (Edit)
    if tool_name == "Write":
        content = tool_input.get("content", "")
    else:  # Edit
        content = tool_input.get("new_string", "")

    if not isinstance(content, str):
        sys.exit(0)

    found, sample = find_hardcode_in_content(content)
    if not found:
        sys.exit(0)

    msg = (
        f"[MUNINN PRE-TOOL HOOK] Blocked {tool_name} introducing hardcoded path.\n"
        f"File: {file_path}\n"
        f"Offending line: {sample}\n\n"
        f"This is enforced by CLAUDE.md RULE 1 (Universal code, never repo-hardcoded).\n"
        f"engine/core/ and muninn/ must NOT contain absolute paths to MUNINN-.\n"
        f"Use one of:\n"
        f"  - _REPO_PATH module global (already managed by Muninn)\n"
        f"  - os.environ.get('MUNINN_REPO', ...)\n"
        f"  - Path(__file__).resolve().parent (relative to module)\n"
        f"  - Function argument passed by caller\n"
        f"Do not retry. Refactor to parameterize the path."
    )
    print(msg, file=sys.stderr)
    sys.exit(2)


if __name__ == "__main__":
    main()
