#!/usr/bin/env python3
"""SessionStart hook — auto-boot Muninn at session start (LIGHT MODE).

Reads SessionStart payload from stdin (Claude Code spec):
  {
    "hook_event_name": "SessionStart",
    "session_id": "...",
    "source": "startup" | "resume" | "clear" | "compact",
    "cwd": "/path/to/repo"
  }

If source in {startup, resume}, reads .muninn/tree/root.mn + the N most
recently modified branches (proxy for "hot"), caps to MAX_INJECT_CHARS,
and emits as additionalContext.

Filters out clear (fresh start) and compact (PreCompact already wrote .mn).

LIGHT MODE: pure file I/O. No engine import, no subprocess, no mycelium
queries. Target: <500ms. Exit 0 always (fail-safe — must not block session).

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import sys
from datetime import datetime
from pathlib import Path


def _log_hook_error(context, exc):
    """Append a swallowed exception to ~/.muninn/hook_errors.log."""
    try:
        engine_core = str(Path(__file__).resolve().parent.parent.parent
                          / "engine" / "core")
        if engine_core not in sys.path:
            sys.path.insert(0, engine_core)
        from _hook_logger import log_hook_event
        log_hook_event("session_start_hook", context, exc)
    except Exception:
        try:
            sys.stderr.write(
                f"[MUNINN HOOK LOG fallback] {datetime.now().isoformat()} "
                f"[session_start_hook:{context}] {type(exc).__name__}: {exc}\n"
            )
            sys.stderr.flush()
        except Exception:
            pass


# Main session has more context room than subagents (subagent cap = 20K),
# but we still cap defensively to avoid swamping the session window.
MAX_INJECT_CHARS = 40000  # ~10K tokens at 4 chars/token average

# Number of recently-modified branches to surface in addition to root.
TOP_RECENT_BRANCHES = 5


def _emit_empty():
    """Output an empty additionalContext, exit 0 (fail-safe)."""
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "SessionStart",
            "additionalContext": "",
        }
    }))
    sys.exit(0)


def _truncate_with_marker(text, max_chars):
    """Truncate text at max_chars, add a clear marker if truncated.

    Same BUG-101-safe pattern as subagent_start_hook: clamp slice index
    at 0 and account for the marker length when computing the slice.
    """
    if max_chars <= 0:
        return ""
    if len(text) <= max_chars:
        return text
    marker = "\n\n[... Muninn boot truncated to fit session context ...]"
    if max_chars <= len(marker):
        return marker[:max_chars]
    slice_end = max(0, max_chars - len(marker))
    return text[:slice_end] + marker


def _find_tree_dir(repo_path):
    """Find the .muninn/tree directory or fall back to memory/."""
    candidates = [
        repo_path / ".muninn" / "tree",
        repo_path / "memory",
    ]
    for c in candidates:
        if c.exists() and c.is_dir():
            return c
    return None


def _read_root(tree_dir):
    """Read root.mn if present."""
    root_file = tree_dir / "root.mn"
    if not root_file.exists():
        return ""
    try:
        return root_file.read_text(encoding="utf-8")
    except OSError:
        return ""


def _find_recent_branches(tree_dir, n):
    """Return up to n (name, text) tuples for the n most recently modified branches.

    "Recent" is a cheap proxy for "hot" — branches touched in the last session
    are most likely relevant when Claude wakes up. Sorted by st_mtime desc.
    """
    branches = []
    try:
        for bf in tree_dir.glob("*.mn"):
            if bf.name == "root.mn":
                continue
            try:
                branches.append((bf.stat().st_mtime, bf))
            except OSError:
                continue
    except OSError:
        return []
    branches.sort(key=lambda t: t[0], reverse=True)
    selected = []
    for _mtime, bf in branches[:n]:
        try:
            selected.append((bf.stem, bf.read_text(encoding="utf-8")))
        except OSError:
            continue
    return selected


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
    except UnicodeDecodeError as e:
        _log_hook_error("stdin_decode", e)
        _emit_empty()
        return
    except Exception as e:
        _log_hook_error("stdin_read", e)
        _emit_empty()
        return
    if not raw.strip():
        _emit_empty()
        return
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as e:
        _log_hook_error("stdin_parse", e)
        _emit_empty()
        return
    except Exception as e:
        _log_hook_error("stdin_unexpected", e)
        _emit_empty()
        return

    if not isinstance(payload, dict):
        _emit_empty()
        return

    source = payload.get("source", "")
    # Only trigger boot injection on real session starts. clear and compact
    # are no-ops here: clear is a deliberate fresh start (user wants empty
    # context), and compact already ran the PreCompact hook which wrote
    # the session .mn — re-injecting would be redundant.
    if source not in ("startup", "resume"):
        _emit_empty()
        return

    repo_path_str = payload.get("cwd") or os.getcwd()
    try:
        repo_path = Path(repo_path_str).resolve()
    except Exception as e:
        _log_hook_error("resolve_cwd", e)
        _emit_empty()
        return

    if not repo_path.exists() or not repo_path.is_dir():
        _emit_empty()
        return

    tree_dir = _find_tree_dir(repo_path)
    if tree_dir is None:
        _emit_empty()
        return

    try:
        root_text = _read_root(tree_dir)
        branches = _find_recent_branches(tree_dir, TOP_RECENT_BRANCHES)

        if not root_text and not branches:
            _emit_empty()
            return

        parts = []
        parts.append(
            f"[MUNINN SESSION BOOT - source={source}]\n"
            f"Auto-loaded from .muninn/tree at {repo_path}.\n"
            f"Includes root.mn + {len(branches)} recently-modified branches "
            f"(proxy for hot memory).\n"
            f"This is memory context, not authoritative truth - verify before acting.\n"
        )
        if root_text:
            parts.append(f"\n=== root.mn ===\n{root_text}")
        for bname, btext in branches:
            parts.append(f"\n=== branch: {bname} ===\n{btext}")

        injected = "\n".join(parts)
        injected = _truncate_with_marker(injected, MAX_INJECT_CHARS)

        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "SessionStart",
                "additionalContext": injected,
            }
        }))
    except Exception as e:
        _log_hook_error("compose_injected_context", e)
        _emit_empty()
        return

    sys.exit(0)


if __name__ == "__main__":
    main()
