#!/usr/bin/env python3
"""SubagentStart hook — inject a LIGHT Muninn slice into spawned sub-agents.

Reads SubagentStart payload from stdin (Claude Code spec):
  {
    "hook_event_name": "SubagentStart",
    "agent_id": "agent-abc123",
    "agent_type": "Explore" (or "Plan", custom name, etc.)
  }

LIGHT MODE: instead of calling muninn.boot() (which runs spreading activation,
L10 cue distillation, KIComp filtering and takes 100+ seconds on large trees),
we directly read root.mn from disk and at most 1-2 branches that name-match
the agent_type. Target: <500ms.

Without this hook, sub-agents spawn with EMPTY Muninn context. With it,
they get the project root summary plus one targeted branch.

Design rules:
- Pure file I/O. No engine import, no mycelium queries, no spreading.
- Cap output hard (sub-agents have small context windows).
- Never raise (exit 0 always — failing hook must not block sub-agent spawn).
- On any failure, output empty additionalContext (fail-safe degradation).

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import sys
from pathlib import Path


# Cap injected context. Sub-agents have small context windows compared
# to main session — keep this conservative.
MAX_INJECT_CHARS = 20000  # ~5000 tokens at 4 chars/token average

# Time budget — soft target. We don't enforce it but we don't do anything
# that would normally exceed it.
SOFT_TIME_BUDGET_MS = 500


def _emit_empty():
    """Output an empty additionalContext, exit 0."""
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "SubagentStart",
            "additionalContext": "",
        }
    }))
    sys.exit(0)


def _truncate_with_marker(text: str, max_chars: int) -> str:
    """Truncate text at max_chars, add a clear marker if truncated."""
    if len(text) <= max_chars:
        return text
    return (
        text[: max_chars - 100]
        + "\n\n[... Muninn slice truncated to fit sub-agent context ...]"
    )


def _find_tree_dir(repo_path: Path) -> Path | None:
    """Find the .muninn/tree directory or fall back to memory/."""
    candidates = [
        repo_path / ".muninn" / "tree",
        repo_path / "memory",
    ]
    for c in candidates:
        if c.exists() and c.is_dir():
            return c
    return None


def _read_root(tree_dir: Path) -> str:
    """Read root.mn if present."""
    root_file = tree_dir / "root.mn"
    if not root_file.exists():
        return ""
    try:
        return root_file.read_text(encoding="utf-8")
    except OSError:
        return ""


def _find_relevant_branch(tree_dir: Path, agent_type: str) -> tuple[str, str]:
    """Find one branch file whose name or content best matches the agent_type.

    Returns (branch_name, branch_text). Empty strings if nothing found.
    """
    if not agent_type:
        return "", ""
    keyword = agent_type.lower()

    # First pass: filename match
    for branch_file in sorted(tree_dir.glob("*.mn")):
        if branch_file.name == "root.mn":
            continue
        if keyword in branch_file.stem.lower():
            try:
                return branch_file.stem, branch_file.read_text(encoding="utf-8")
            except OSError:
                continue

    # Second pass: content match — read the first 200 chars of each branch
    # and check if the keyword appears (cheap heuristic, no full scan)
    for branch_file in sorted(tree_dir.glob("*.mn")):
        if branch_file.name == "root.mn":
            continue
        try:
            head = branch_file.read_text(encoding="utf-8")[:500]
            if keyword in head.lower():
                return branch_file.stem, branch_file.read_text(encoding="utf-8")
        except OSError:
            continue

    return "", ""


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
        payload = json.loads(raw)
    except Exception:
        _emit_empty()
        return

    if not isinstance(payload, dict):
        _emit_empty()
        return

    agent_type = payload.get("agent_type", "")
    repo_path_str = payload.get("cwd") or os.getcwd()
    repo_path = Path(repo_path_str).resolve()

    tree_dir = _find_tree_dir(repo_path)
    if tree_dir is None:
        _emit_empty()
        return

    try:
        root_text = _read_root(tree_dir)
        branch_name, branch_text = _find_relevant_branch(tree_dir, agent_type)

        # Compose the injected context
        parts = []
        parts.append(
            f"[MUNINN LIGHT BOOT for {agent_type or 'subagent'}]\n"
            f"You are a sub-agent with read access to Sky's Muninn memory tree "
            f"at {repo_path}.\n"
            f"This is a LIGHT slice (root + 1 branch). For more context, read "
            f".muninn/tree/ or memory/ directly.\n"
            f"Use it as background, not as truth — verify before acting.\n"
        )
        if root_text:
            parts.append(f"\n=== root.mn ===\n{root_text}")
        if branch_text:
            parts.append(f"\n=== branch: {branch_name} ===\n{branch_text}")

        if not root_text and not branch_text:
            _emit_empty()
            return

        injected = "\n".join(parts)
        injected = _truncate_with_marker(injected, MAX_INJECT_CHARS)

        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "SubagentStart",
                "additionalContext": injected,
            }
        }))
    except Exception:
        _emit_empty()
        return

    sys.exit(0)


if __name__ == "__main__":
    main()
