#!/usr/bin/env python3
"""SubagentStart hook — inject a LIGHT Muninn slice into spawned sub-agents.

Reads SubagentStart payload from stdin (Claude Code spec).

LIGHT MODE: instead of calling muninn.boot() (which runs spreading activation,
L10 cue distillation, KIComp filtering and takes 100+ seconds on large trees),
we directly read root.mn from disk and at most 1 branch that name-matches
the agent_type. Target: <500ms.

Design rules:
- Pure file I/O. No engine import, no mycelium queries, no spreading.
- Cap output hard.
- Never raise (exit 0 always).
- On any failure, emit empty additionalContext (fail-safe).

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import sys
from pathlib import Path

# --- PIPELINE_TRACE block (removable, see docs/PIPELINE_TRACE_REMOVAL.md) ---  # PIPELINE_TRACE
try:  # PIPELINE_TRACE
    _pt_dir = str(Path(__file__).resolve().parent.parent.parent / "engine" / "core")  # PIPELINE_TRACE
    if _pt_dir not in sys.path: sys.path.insert(0, _pt_dir)  # PIPELINE_TRACE
    from pipeline_trace import log_event  # PIPELINE_TRACE
except Exception:  # PIPELINE_TRACE
    def log_event(*a, **kw): pass  # PIPELINE_TRACE
# --- end PIPELINE_TRACE block ---  # PIPELINE_TRACE

MAX_INJECT_CHARS = 20000  # ~5000 tokens


def _emit_empty():
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "SubagentStart",
            "additionalContext": "",
        }
    }))
    sys.exit(0)


def _truncate_with_marker(text, max_chars):
    # BUG-101 fix (audit 2026-04-10): clamp negative slice and account for
    # marker length, otherwise small max_chars produces oversized output.
    if max_chars <= 0:
        return ""
    if len(text) <= max_chars:
        return text
    marker = "\n\n[... Muninn slice truncated to fit sub-agent context ...]"
    if max_chars <= len(marker):
        return marker[:max_chars]
    slice_end = max(0, max_chars - len(marker))
    return text[:slice_end] + marker


def _find_tree_dir(repo_path):
    candidates = [
        repo_path / ".muninn" / "tree",
        repo_path / "memory",
    ]
    for c in candidates:
        if c.exists() and c.is_dir():
            return c
    return None


def _read_root(tree_dir):
    root_file = tree_dir / "root.mn"
    if not root_file.exists():
        return ""
    try:
        return root_file.read_text(encoding="utf-8")
    except OSError:
        return ""


def _find_relevant_branch(tree_dir, agent_type):
    if not agent_type:
        return "", ""
    keyword = agent_type.lower()
    for branch_file in sorted(tree_dir.glob("*.mn")):
        if branch_file.name == "root.mn":
            continue
        if keyword in branch_file.stem.lower():
            try:
                return branch_file.stem, branch_file.read_text(encoding="utf-8")
            except OSError:
                continue
    for branch_file in sorted(tree_dir.glob("*.mn")):
        if branch_file.name == "root.mn":
            continue
        try:
            head = branch_file.read_text(encoding="utf-8")[:500]
            if keyword in head.lower():
                return branch_file.stem, branch_file.read_text(encoding="utf-8")
        except OSError:
            continue
    return "", ""


def _log_subagent_error(context, exc):
    """2026-05-13 drift-fix : restore audit trail (F5 regression)."""
    try:
        engine_core = str(Path(__file__).resolve().parent.parent.parent
                          / "engine" / "core")
        if engine_core not in sys.path:
            sys.path.insert(0, engine_core)
        from _hook_logger import log_hook_event
        log_hook_event("subagent_start_hook", context, exc)
    except Exception:
        try:
            sys.stderr.write(
                f"[MUNINN HOOK LOG fallback] [subagent_start_hook:"
                f"{{context}}] {{type(exc).__name__}}: {{exc}}\n"
            )
        except Exception:
            pass


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
    except (UnicodeDecodeError, OSError) as e:
        _log_subagent_error("stdin_decode", e)
        _emit_empty()
        return
    try:
        payload = json.loads(raw)
    except (json.JSONDecodeError, ValueError) as e:
        _log_subagent_error("stdin_parse", e)
        _emit_empty()
        return
    except Exception as e:
        _log_subagent_error("stdin_unexpected", e)
        _emit_empty()
        return

    if not isinstance(payload, dict):
        _emit_empty()
        return

    agent_type = payload.get("agent_type", "")
    log_event("pipeline.hook.subagent_start.begin", {"agent_type": agent_type})  # PIPELINE_TRACE
    repo_path_str = payload.get("cwd") or os.getcwd()
    repo_path = Path(repo_path_str).resolve()

    tree_dir = _find_tree_dir(repo_path)
    if tree_dir is None:
        _emit_empty()
        return

    try:
        root_text = _read_root(tree_dir)
        branch_name, branch_text = _find_relevant_branch(tree_dir, agent_type)

        parts = []
        parts.append(
            f"[MUNINN LIGHT BOOT for {agent_type or 'subagent'}]\n"
            f"You are a sub-agent with read access to Sky's Muninn memory tree "
            f"at {repo_path}.\n"
            f"This is a LIGHT slice (root + 1 branch). For more context, read "
            f".muninn/tree/ or memory/ directly.\n"
            f"Use it as background, not as truth - verify before acting.\n"
        )
        if root_text:
            parts.append(f"\n=== root.mn ===\n{root_text}")
        if branch_text:
            parts.append(f"\n=== branch: {branch_name} ===\n{branch_text}")

        if not root_text and not branch_text:
            _emit_empty()
            return

        injected = "\n".join(parts)
        injected = _truncate_with_marker(injected, MAX_INJECT_CHARS)
        log_event("pipeline.hook.subagent_start.emit", {"agent_type": agent_type, "len": len(injected), "branch": branch_name})  # PIPELINE_TRACE

        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "SubagentStart",
                "additionalContext": injected,
            }
        }))
    except Exception as e:
        _log_subagent_error("compose_injected_context", e)
        _emit_empty()
        return

    sys.exit(0)


if __name__ == "__main__":
    main()
