#!/usr/bin/env python3
"""SubagentStart hook — inject Muninn boot context into spawned sub-agents.

Reads SubagentStart payload from stdin (Claude Code spec):
  {
    "hook_event_name": "SubagentStart",
    "agent_id": "agent-abc123",
    "agent_type": "Explore" (or "Plan", custom name, etc.)
  }

Calls muninn.boot(query=agent_type) to get a relevant slice of the tree
(root + branches matching the agent's purpose), caps the result to ~5000
tokens (configurable), and writes a JSON response with hookSpecificOutput
so Claude Code injects it into the sub-agent's initial context.

Without this hook, sub-agents spawn with EMPTY Muninn context — they have
no idea what Sky's tree contains, what decisions exist, what errors are
known. This hook closes that gap.

Design rules:
- Cap tokens hard (sub-agent context is precious, ~5K tokens max).
- Never raise (exit 0 always — failing hook must not block sub-agent spawn).
- On any failure, output empty additionalContext (sub-agent boots without
  Muninn, same as before this hook existed — fail-safe degradation).

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import sys
from pathlib import Path


# Cap injected context. Sub-agents have small context windows compared
# to main session — keep this conservative.
MAX_INJECT_CHARS = 20000  # ~5000 tokens at 4 chars/token average


def _emit_empty():
    """Output an empty additionalContext, exit 0."""
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "SubagentStart",
            "additionalContext": "",
        }
    }))
    sys.exit(0)


def _truncate_with_marker(text: str, max_chars: int) -> str:
    """Truncate text at max_chars, add a clear marker if truncated."""
    if len(text) <= max_chars:
        return text
    return (
        text[: max_chars - 100]
        + "\n\n[... Muninn boot truncated to fit sub-agent context ...]"
    )


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
        payload = json.loads(raw)
    except Exception:
        _emit_empty()
        return

    if not isinstance(payload, dict):
        _emit_empty()
        return

    agent_type = payload.get("agent_type", "")
    repo_path = payload.get("cwd") or os.getcwd()

    # Resolve engine/core path. Try a few common locations.
    possible_engine_dirs = [
        Path(repo_path) / "engine" / "core",
        Path(repo_path) / "muninn",
    ]
    engine_dir = None
    for p in possible_engine_dirs:
        if (p / "muninn.py").exists() or (p / "_engine.py").exists():
            engine_dir = p
            break

    if engine_dir is None:
        _emit_empty()
        return

    if str(engine_dir) not in sys.path:
        sys.path.insert(0, str(engine_dir))

    try:
        import muninn

        muninn._REPO_PATH = Path(repo_path).resolve()
        muninn._refresh_tree_paths()

        # Use agent_type as query so boot picks branches relevant to the
        # sub-agent's purpose. Falls back to empty query (= last session).
        query = agent_type or ""
        boot_text = muninn.boot(query=query)

        if not boot_text:
            _emit_empty()
            return

        # Cap and wrap with a header so the sub-agent knows what it sees.
        capped = _truncate_with_marker(boot_text, MAX_INJECT_CHARS)
        header = (
            f"[MUNINN BOOT for {agent_type or 'subagent'}]\n"
            f"You are a sub-agent with read access to Sky's Muninn memory tree.\n"
            f"Below is the relevant slice for your task. Use it as background "
            f"context, not as truth — verify before acting.\n\n"
        )
        injected = header + capped

        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "SubagentStart",
                "additionalContext": injected,
            }
        }))
    except Exception:
        _emit_empty()
        return

    sys.exit(0)


if __name__ == "__main__":
    main()
