#!/usr/bin/env python3
"""Property-based tests for sentiment.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'engine\\core'))

from hypothesis import given, strategies as st, settings
from engine.core.sentiment import *

@given(text=st.text(max_size=100))
@settings(max_examples=50)
def test_score_sentiment_no_crash(text):
    """Smoke: score_sentiment() does not crash on arbitrary input"""
    # from engine.core.sentiment import score_sentiment
    try:
        score_sentiment(text)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(messages=st.text(max_size=50))
@settings(max_examples=50)
def test_score_session_no_crash(messages):
    """Smoke: score_session() does not crash on arbitrary input"""
    # from engine.core.sentiment import score_session
    try:
        score_session(messages)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(valence=st.floats(allow_nan=False, allow_infinity=False), arousal=st.floats(allow_nan=False, allow_infinity=False))
@settings(max_examples=50)
def test_circumplex_map_no_crash(valence, arousal):
    """Smoke: circumplex_map() does not crash on arbitrary input"""
    # from engine.core.sentiment import circumplex_map
    try:
        circumplex_map(valence, arousal)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK
