#!/usr/bin/env python3
"""Property-based tests for budget_select.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from hypothesis import given, strategies as st, settings
from engine.core.budget_select import *

@given(chunk=st.text(max_size=100))
@settings(max_examples=50)
def test_has_fact_span_no_crash(chunk):
    """Smoke: has_fact_span() does not crash on arbitrary input"""
    # from engine.core.budget_select import has_fact_span
    try:
        has_fact_span(chunk)
    except (ValueError, TypeError, KeyError, IndexError):
        pass  # Expected rejections are OK

@given(chunks=st.text(max_size=50))
@settings(max_examples=50)
def test_compute_idf_no_crash(chunks):
    """Smoke: compute_idf() does not crash on arbitrary input"""
    # from engine.core.budget_select import compute_idf
    try:
        compute_idf(chunks)
    except (ValueError, TypeError, KeyError, IndexError):
        pass  # Expected rejections are OK

@given(chunk=st.text(max_size=100), idf_map=st.dictionaries(st.text(max_size=10), st.integers(), max_size=10), position_idx=st.integers(-1000, 1000), total_chunks=st.integers(-1000, 1000))
@settings(max_examples=50)
def test_score_chunk_no_crash(chunk, idf_map, position_idx, total_chunks):
    """Smoke: score_chunk() does not crash on arbitrary input"""
    # from engine.core.budget_select import score_chunk
    try:
        score_chunk(chunk, idf_map, position_idx, total_chunks)
    except (ValueError, TypeError, KeyError, IndexError):
        pass  # Expected rejections are OK

@given(chunks=st.text(max_size=50), budget_tokens=st.integers(-1000, 1000), token_count=st.text(max_size=50), keep_facts=st.booleans())
@settings(max_examples=50)
def test_select_chunks_no_crash(chunks, budget_tokens, token_count, keep_facts):
    """Smoke: select_chunks() does not crash on arbitrary input"""
    # from engine.core.budget_select import select_chunks
    try:
        select_chunks(chunks, budget_tokens, token_count, keep_facts)
    except (ValueError, TypeError, KeyError, IndexError):
        pass  # Expected rejections are OK

@given(text=st.text(max_size=100), budget_tokens=st.integers(-1000, 1000), token_count=st.text(max_size=50), keep_facts=st.booleans(), separator=st.text(max_size=100))
@settings(max_examples=50)
def test_budget_select_no_crash(text, budget_tokens, token_count, keep_facts, separator):
    """Smoke: budget_select() does not crash on arbitrary input"""
    # from engine.core.budget_select import budget_select
    try:
        budget_select(text, budget_tokens, token_count, keep_facts, separator)
    except (ValueError, TypeError, KeyError, IndexError):
        pass  # Expected rejections are OK

@given(text=st.text(max_size=100), chunks=st.text(max_size=50), budget_tokens=st.integers(-1000, 1000))
@settings(max_examples=50)
def test_stats_no_crash(text, chunks, budget_tokens):
    """Smoke: stats() does not crash on arbitrary input"""
    # from engine.core.budget_select import stats
    try:
        stats(text, chunks, budget_tokens)
    except (ValueError, TypeError, KeyError, IndexError):
        pass  # Expected rejections are OK
