#!/usr/bin/env python3
"""Property-based tests for muninn_layers.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest
from hypothesis import given, strategies as st, settings
from engine.core.muninn_layers import *
# forge: the following functions were SKIPPED because they have
# side effects (write to disk, run subprocess, hit network).
# Fuzzing them without isolation would corrupt the repo.
# To test them, write isolated tests by hand using tmp_path.
#   - compress_file  (path arg + .read_text())
#   - verify_compression  (path arg + .read_text())



# cwd guard: the destructive detector catches direct mkdir/write/open
# calls in fuzzed function bodies, but it does not follow indirect calls
# (e.g. parse_input() -> IndexBuilder() -> mkdir()). When Hypothesis fuzzes
# a path-like arg with a random string like '0' or '\xfeQ', the indirect
# mkdir resolves it relative to cwd and pollutes the repo root.
# This autouse fixture chdir's into tmp_path before each test, so any
# indirect file-system mutation lands in a sandbox pytest cleans up.
@pytest.fixture(autouse=True)
def _forge_isolate_cwd(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

@given(repo_path=st.text(max_size=50))
@settings(max_examples=50)
def test_load_codebook_no_crash(repo_path):
    """Smoke: load_codebook() does not crash on arbitrary input"""
    # from engine.core.muninn_layers import load_codebook
    try:
        load_codebook(repo_path)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(line=st.text(max_size=50))
@settings(max_examples=50)
def test_compress_line_no_crash(line):
    """Smoke: compress_line() does not crash on arbitrary input"""
    # from engine.core.muninn_layers import compress_line
    try:
        compress_line(line)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(text=st.text(max_size=100))
@settings(max_examples=50)
def test_extract_facts_no_crash(text):
    """Smoke: extract_facts() does not crash on arbitrary input"""
    # from engine.core.muninn_layers import extract_facts
    try:
        extract_facts(text)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(line=st.text(max_size=100))
@settings(max_examples=50)
def test_tag_memory_type_no_crash(line):
    """Smoke: tag_memory_type() does not crash on arbitrary input"""
    # from engine.core.muninn_layers import tag_memory_type
    try:
        tag_memory_type(line)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(header=st.text(max_size=100), lines=st.text(max_size=50))
@settings(max_examples=50)
def test_compress_section_no_crash(header, lines):
    """Smoke: compress_section() does not crash on arbitrary input"""
    # from engine.core.muninn_layers import compress_section
    try:
        compress_section(header, lines)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(line=st.text(max_size=100))
@settings(max_examples=50)
def test_decode_line_no_crash(line):
    """Smoke: decode_line() does not crash on arbitrary input"""
    # from engine.core.muninn_layers import decode_line
    try:
        decode_line(line)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK
