#!/usr/bin/env python3
"""Property-based tests for sync_backend.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'engine\\core'))

from hypothesis import given, strategies as st, settings
from engine.core.sync_backend import *
# BUG-102 (forge): the following functions were SKIPPED because
# they have side effects (write to disk, run subprocess, hit
# network). Fuzzing them without isolation would corrupt the repo.
# To test them, write isolated tests by hand using tmp_path.
#   - save_sync_config  (name matches /^save/)
#   - sync_metrics  (name matches /^sync_/)
#   - migrate_backend  (name matches /^migrate/)
#   - sync_doctor  (name matches /^sync_/)
#   - export_meta_json  (calls .write_text())
#   - import_meta_json  (calls .mkdir())


@given(path=st.text(max_size=50), min_mb=st.integers(-1000, 1000))
@settings(max_examples=50)
def test_check_disk_space_no_crash(path, min_mb):
    """Smoke: check_disk_space() does not crash on arbitrary input"""
    # from engine.core.sync_backend import check_disk_space
    try:
        check_disk_space(path, min_mb)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(config=st.dictionaries(st.text(max_size=10), st.integers(), max_size=10))
@settings(max_examples=50)
def test_get_sync_backend_no_crash(config):
    """Smoke: get_sync_backend() does not crash on arbitrary input"""
    # from engine.core.sync_backend import get_sync_backend
    try:
        get_sync_backend(config)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK
