#!/usr/bin/env python3
"""Property-based tests for _secrets.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from hypothesis import given, strategies as st, settings
from engine.core._secrets import *

@given(text=st.text(max_size=100))
@settings(max_examples=50, deadline=None)
def test_redact_secrets_text_no_crash(text):
    """Smoke: redact_secrets_text() does not crash on arbitrary input"""
    # Property test for redact_secrets_text
    try:
        redact_secrets_text(text)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(text=st.text(max_size=100))
@settings(max_examples=50, deadline=None)
def test_count_chained_commands_no_crash(text):
    """Smoke: count_chained_commands() does not crash on arbitrary input"""
    # Property test for count_chained_commands
    try:
        count_chained_commands(text)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(text=st.text(max_size=100), max_chains=st.integers(-1000, 1000))
@settings(max_examples=50, deadline=None)
def test_clamp_chained_commands_no_crash(text, max_chains):
    """Smoke: clamp_chained_commands() does not crash on arbitrary input"""
    # Property test for clamp_chained_commands
    try:
        clamp_chained_commands(text, max_chains)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK
