"""I.2 — Anti-zombie : public functions without callers should be wired or removed.

A "zombie" function is one defined at module level, not prefixed with `_`,
and never referenced anywhere in the shipped code (engine/, muninn/,
.claude/hooks/) or tests/. The audit reported ~89 candidates.

Phase J will refactor systematically (delete or whitelist). This test
enumerates the current set + xfails strict=False with the count so the
ratchet bites only when the count GROWS.

Whitelisted reasons :
  - method-like helpers exposed for tests (e.g. main(), compute_repo)
  - intentional public API consumed externally (CLI entry points)
  - decorator-registered tools (FastMCP `@app.tool()`)
"""
from __future__ import annotations

import ast
import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent

# Functions whose existence is meaningful even without literal grep hits.
WHITELIST_INTENTIONAL = {
    "main",                  # console script entry points (called via setup.py scripts)
    "doctor",                # exposed as CLI subcommand
    "main_window",           # PyQt class — auto-loaded by Qt registration
    "to_json", "from_json",  # serialization dunders for dataclasses
    "save", "load", "close", "open",  # standard lifecycle methods
}


def _list_public_module_functions() -> list[tuple[str, str]]:
    """Return (module_path, function_name) for every module-level public def."""
    out: list[tuple[str, str]] = []
    for sub in ("engine", "muninn"):
        for py in (REPO_ROOT / sub).rglob("*.py"):
            if "__pycache__" in py.parts or "experimental" in py.parts:
                continue
            try:
                tree = ast.parse(py.read_text(encoding="utf-8"))
            except (SyntaxError, UnicodeDecodeError):
                continue
            for node in tree.body:
                if (isinstance(node, ast.FunctionDef)
                        and not node.name.startswith("_")
                        and node.name not in WHITELIST_INTENTIONAL):
                    out.append((str(py.relative_to(REPO_ROOT)), node.name))
    return out


def _shipped_text() -> str:
    """All shipped + test source as one string for grep."""
    chunks: list[str] = []
    for root in ("engine", "muninn", "tests"):
        for py in (REPO_ROOT / root).rglob("*.py"):
            if "__pycache__" in py.parts:
                continue
            try:
                chunks.append(py.read_text(encoding="utf-8", errors="ignore"))
            except OSError:
                continue
    for hk in (REPO_ROOT / ".claude" / "hooks").glob("*.py"):
        try:
            chunks.append(hk.read_text(encoding="utf-8", errors="ignore"))
        except OSError:
            continue
    return "\n".join(chunks)


def _find_zombies() -> list[tuple[str, str]]:
    body = _shipped_text()
    zombies = []
    for path, fn in _list_public_module_functions():
        # Find all occurrences of the function name (word-boundary), skip
        # the file where it's defined.
        try:
            file_text = (REPO_ROOT / path).read_text(encoding="utf-8")
        except OSError:
            file_text = ""
        pattern = re.compile(rf"\b{re.escape(fn)}\b")
        total = len(pattern.findall(body))
        self_count = len(pattern.findall(file_text))
        external_uses = total - self_count
        if external_uses <= 0:
            zombies.append((path, fn))
    return zombies


# Captured 2026-05-12 (real count 35; audit overclaim said 89).
# Cushion of +5 over current actual so a single legitimate addition
# doesn't break CI immediately. Phase J refactor will lower further.
ZOMBIE_COUNT_BASELINE = 40


@pytest.mark.xfail(
    reason="Phase J refactor needed: enumerate + decide wire/delete/whitelist. "
           "Initial baseline captured 2026-05-12; this test ratchets the "
           "count downward over time.",
    strict=False,
)
def test_i2_zombie_count_below_baseline() -> None:
    zombies = _find_zombies()
    # Always write the current list so Sky can inspect.
    log = REPO_ROOT / "tests" / "_zombie_function_inventory.txt"
    log.write_text(
        f"# Generated by test_i2_no_zombie_function — {len(zombies)} zombies\n"
        + "\n".join(f"{p}:{fn}" for p, fn in zombies),
        encoding="utf-8",
    )
    assert len(zombies) <= ZOMBIE_COUNT_BASELINE, (
        f"Zombie function count grew: {len(zombies)} > baseline "
        f"{ZOMBIE_COUNT_BASELINE}. See tests/_zombie_function_inventory.txt"
    )


def test_i2_baseline_not_inflated() -> None:
    """Ratchet down: if cleanup happened, baseline must drop too.

    Tolerates noise of ±10 around the baseline. If zombie count falls
    >10 below baseline (e.g. Phase J cleanup), bump baseline down to
    the new actual + small cushion.
    """
    zombies = _find_zombies()
    if len(zombies) < ZOMBIE_COUNT_BASELINE - 10:
        pytest.fail(
            f"Cleanup detected: only {len(zombies)} zombies vs baseline "
            f"{ZOMBIE_COUNT_BASELINE}. Lower ZOMBIE_COUNT_BASELINE in this "
            f"test file to lock in the gain (recommended: actual + 5)."
        )
