#!/usr/bin/env python3
"""Property-based tests for mycelium_db.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest
from hypothesis import given, strategies as st, settings
from engine.core.mycelium_db import *


# cwd guard: the destructive detector catches direct mkdir/write/open
# calls in fuzzed function bodies, but it does not follow indirect calls
# (e.g. parse_input() -> IndexBuilder() -> mkdir()). When Hypothesis fuzzes
# a path-like arg with a random string like '0' or '\xfeQ', the indirect
# mkdir resolves it relative to cwd and pollutes the repo root.
# This autouse fixture chdir's into tmp_path before each test, so any
# indirect file-system mutation lands in a sandbox pytest cleans up.
@pytest.fixture(autouse=True)
def _forge_isolate_cwd(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

@given(d=st.text(max_size=100))
@settings(max_examples=50)
def test_date_to_days_no_crash(d):
    """Smoke: date_to_days() does not crash on arbitrary input"""
    # from engine.core.mycelium_db import date_to_days
    try:
        date_to_days(d)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(days=st.text(max_size=50))
@settings(max_examples=50)
def test_days_to_date_no_crash(days):
    """Smoke: days_to_date() does not crash on arbitrary input"""
    # from engine.core.mycelium_db import days_to_date
    try:
        days_to_date(days)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK
