#!/usr/bin/env python3
"""Property-based tests for _tree_renderer.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest

# _tree_renderer.py top-level imports PIL (`from PIL import Image, ...`)
# which is an optional dep (PIL is pulled in transitively via PyQt6 locally,
# but the CI Validate job runs a minimal install). Skip the whole module
# when Pillow is absent so the renderer's property tests don't break CI.
pytest.importorskip("PIL")

from hypothesis import given, strategies as st, settings
from muninn.ui._tree_renderer import *


# cwd guard: the destructive detector catches direct mkdir/write/open
# calls in fuzzed function bodies, but it does not follow indirect calls
# (e.g. parse_input() -> IndexBuilder() -> mkdir()). When Hypothesis fuzzes
# a path-like arg with a random string like '0' or '\xfeQ', the indirect
# mkdir resolves it relative to cwd and pollutes the repo root.
# This autouse fixture chdir's into tmp_path before each test, so any
# indirect file-system mutation lands in a sandbox pytest cleans up.
@pytest.fixture(autouse=True)
def _forge_isolate_cwd(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

@given(scan_path=st.text(max_size=50), output_path=st.text(max_size=50))
@settings(max_examples=50)
def test_render_no_crash(scan_path, output_path):
    """Smoke: render() does not crash on arbitrary input"""
    # from muninn.ui._tree_renderer import render
    try:
        render(scan_path, output_path)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK
