#!/usr/bin/env python3
"""Property-based tests for dedup.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'engine/core'))

import pytest
from hypothesis import given, strategies as st, settings
from engine.core.dedup import *


# BUG-102 cwd guard (added 2026-05-07): the destructive detector
# catches direct mkdir/write/open calls in fuzzed function bodies,
# but it does not follow indirect calls (e.g. extract_tags() ->
# Mycelium() -> mkdir()). When Hypothesis fuzzes a path-like arg
# with a random string like '0' or '\xfeQ', the indirect mkdir
# resolves it relative to cwd and pollutes the repo root.
# This autouse fixture chdir's into a tmp_path before each test,
# so any indirect file-system mutation lands in a sandbox that
# pytest cleans up automatically.
@pytest.fixture(autouse=True)
def _forge_isolate_cwd(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

@given(text=st.text(max_size=100), bits=st.integers(-1000, 1000), shingle_size=st.integers(-1000, 1000))
@settings(max_examples=50)
def test_simhash_no_crash(text, bits, shingle_size):
    """Smoke: simhash() does not crash on arbitrary input"""
    # from engine.core.dedup import simhash
    try:
        simhash(text, bits, shingle_size)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(a=st.integers(-1000, 1000), b=st.integers(-1000, 1000))
@settings(max_examples=50)
def test_hamming_distance_no_crash(a, b):
    """Smoke: hamming_distance() does not crash on arbitrary input"""
    # from engine.core.dedup import hamming_distance
    try:
        hamming_distance(a, b)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(a=st.text(max_size=100), b=st.text(max_size=100), threshold=st.integers(-1000, 1000), bits=st.integers(-1000, 1000), shingle_size=st.integers(-1000, 1000))
@settings(max_examples=50)
def test_similar_no_crash(a, b, threshold, bits, shingle_size):
    """Smoke: similar() does not crash on arbitrary input"""
    # from engine.core.dedup import similar
    try:
        similar(a, b, threshold, bits, shingle_size)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(lines=st.text(max_size=50), threshold=st.integers(-1000, 1000), bits=st.integers(-1000, 1000), shingle_size=st.integers(-1000, 1000), min_length=st.integers(-1000, 1000))
@settings(max_examples=50)
def test_dedup_lines_no_crash(lines, threshold, bits, shingle_size, min_length):
    """Smoke: dedup_lines() does not crash on arbitrary input"""
    # from engine.core.dedup import dedup_lines
    try:
        dedup_lines(lines, threshold, bits, shingle_size, min_length)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(text=st.text(max_size=100), threshold=st.integers(-1000, 1000), bits=st.integers(-1000, 1000), shingle_size=st.integers(-1000, 1000), min_length=st.integers(-1000, 1000))
@settings(max_examples=50)
def test_dedup_paragraphs_no_crash(text, threshold, bits, shingle_size, min_length):
    """Smoke: dedup_paragraphs() does not crash on arbitrary input"""
    # from engine.core.dedup import dedup_paragraphs
    try:
        dedup_paragraphs(text, threshold, bits, shingle_size, min_length)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(text=st.text(max_size=100), lines=st.text(max_size=50))
@settings(max_examples=50)
def test_stats_no_crash(text, lines):
    """Smoke: stats() does not crash on arbitrary input"""
    # from engine.core.dedup import stats
    try:
        stats(text, lines)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK
