#!/usr/bin/env python3
"""Property-based tests for _tree_engine.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest
from hypothesis import given, strategies as st, settings
from muninn.ui._tree_engine import *
# forge: the following functions were SKIPPED because they have
# side effects (write to disk, run subprocess, hit network).
# Fuzzing them without isolation would corrupt the repo.
# To test them, write isolated tests by hand using tmp_path.
#   - scan_repo  (path arg + .walk())
#   - main  (calls .makedirs())



# cwd guard: the destructive detector catches direct mkdir/write/open
# calls in fuzzed function bodies, but it does not follow indirect calls
# (e.g. parse_input() -> IndexBuilder() -> mkdir()). When Hypothesis fuzzes
# a path-like arg with a random string like '0' or '\xfeQ', the indirect
# mkdir resolves it relative to cwd and pollutes the repo root.
# This autouse fixture chdir's into tmp_path before each test, so any
# indirect file-system mutation lands in a sandbox pytest cleans up.
@pytest.fixture(autouse=True)
def _forge_isolate_cwd(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

@given(name=st.text(max_size=50), desc=st.text(max_size=50), structure=st.text(max_size=50), output=st.text(max_size=50), deps=st.text(max_size=50))
@settings(max_examples=50)
def test_classify_auto_no_crash(name, desc, structure, output, deps):
    """Smoke: classify_auto() does not crash on arbitrary input"""
    # from muninn.ui._tree_engine import classify_auto
    try:
        classify_auto(name, desc, structure, output, deps)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(filepath=st.text(max_size=50))
@settings(max_examples=50)
def test_load_tree_no_crash(filepath):
    """Smoke: load_tree() does not crash on arbitrary input"""
    # from muninn.ui._tree_engine import load_tree
    try:
        load_tree(filepath)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK
