#!/usr/bin/env python3
"""Property-based tests for bible_scraper.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest
from hypothesis import given, strategies as st, settings
from engine.core.scanner.bible_scraper import *
# forge: the following functions were SKIPPED because they have
# side effects (write to disk, run subprocess, hit network).
# Fuzzing them without isolation would corrupt the repo.
# To test them, write isolated tests by hand using tmp_path.
#   - scrape_bible  (calls .mkdir())



# cwd guard: the destructive detector catches direct mkdir/write/open
# calls in fuzzed function bodies, but it does not follow indirect calls
# (e.g. parse_input() -> IndexBuilder() -> mkdir()). When Hypothesis fuzzes
# a path-like arg with a random string like '0' or '\xfeQ', the indirect
# mkdir resolves it relative to cwd and pollutes the repo root.
# This autouse fixture chdir's into tmp_path before each test, so any
# indirect file-system mutation lands in a sandbox pytest cleans up.
@pytest.fixture(autouse=True)
def _forge_isolate_cwd(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

@given(xml_path=st.text(max_size=50))
@settings(max_examples=50)
def test_scrape_cwe_no_crash(xml_path):
    """Smoke: scrape_cwe() does not crash on arbitrary input"""
    # from engine.core.scanner.bible_scraper import scrape_cwe
    try:
        scrape_cwe(xml_path)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(rules_dir=st.text(max_size=50))
@settings(max_examples=50)
def test_scrape_semgrep_no_crash(rules_dir):
    """Smoke: scrape_semgrep() does not crash on arbitrary input"""
    # from engine.core.scanner.bible_scraper import scrape_semgrep
    try:
        scrape_semgrep(rules_dir)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK
