#!/usr/bin/env python3
"""Property-based tests for muninn.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest
from hypothesis import given, strategies as st, settings
from engine.core.muninn import *
# forge: the following functions were SKIPPED because they have
# side effects (write to disk, run subprocess, hit network).
# Fuzzing them without isolation would corrupt the repo.
# To test them, write isolated tests by hand using tmp_path.
#   - iter_scannable_files  (path arg + .rglob())
#   - scan_repo  (calls .mkdir())
#   - analyze_file  (path arg + .read_text())
#   - bootstrap_mycelium  (path arg + .read_text())
#   - generate_root_mn  (calls .mkdir())
#   - generate_winter_tree  (calls .write_text())
#   - main  (calls .mkdir())



# cwd guard: the destructive detector catches direct mkdir/write/open
# calls in fuzzed function bodies, but it does not follow indirect calls
# (e.g. parse_input() -> IndexBuilder() -> mkdir()). When Hypothesis fuzzes
# a path-like arg with a random string like '0' or '\xfeQ', the indirect
# mkdir resolves it relative to cwd and pollutes the repo root.
# This autouse fixture chdir's into tmp_path before each test, so any
# indirect file-system mutation lands in a sandbox pytest cleans up.
@pytest.fixture(autouse=True)
def _forge_isolate_cwd(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

@given(path=st.text(max_size=50), max_bytes=st.integers(-1000, 1000))
@settings(max_examples=50)
def test_is_scannable_text_no_crash(path, max_bytes):
    """Smoke: is_scannable_text() does not crash on arbitrary input"""
    # from engine.core.muninn import is_scannable_text
    try:
        is_scannable_text(path, max_bytes)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK
