#!/usr/bin/env python3
"""Property-based tests for tokenizer.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'engine\\core'))

from hypothesis import given, strategies as st, settings
from engine.core.tokenizer import *

@given(text=st.text(max_size=100))
@settings(max_examples=50)
def test_count_tokens_no_crash(text):
    """Smoke: count_tokens() does not crash on arbitrary input"""
    # from engine.core.tokenizer import count_tokens
    try:
        count_tokens(text)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(text=st.text(max_size=100))
@settings(max_examples=50)
def test_token_count_no_crash(text):
    """Smoke: token_count() does not crash on arbitrary input"""
    # from engine.core.tokenizer import token_count
    try:
        token_count(text)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK
