#!/usr/bin/env python3
"""Property-based tests for lang_lexicons.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest
from hypothesis import given, strategies as st, settings
from engine.core.lang_lexicons import *


# cwd guard: the destructive detector catches direct mkdir/write/open
# calls in fuzzed function bodies, but it does not follow indirect calls
# (e.g. parse_input() -> IndexBuilder() -> mkdir()). When Hypothesis fuzzes
# a path-like arg with a random string like '0' or '\xfeQ', the indirect
# mkdir resolves it relative to cwd and pollutes the repo root.
# This autouse fixture chdir's into tmp_path before each test, so any
# indirect file-system mutation lands in a sandbox pytest cleans up.
@pytest.fixture(autouse=True)
def _forge_isolate_cwd(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

@given(lang=st.text(max_size=100))
@settings(max_examples=50)
def test_get_lexicon_no_crash(lang):
    """Smoke: get_lexicon() does not crash on arbitrary input"""
    # from engine.core.lang_lexicons import get_lexicon
    try:
        get_lexicon(lang)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(lang=st.text(max_size=100))
@settings(max_examples=50)
def test_format_lexicon_prompt_no_crash(lang):
    """Smoke: format_lexicon_prompt() does not crash on arbitrary input"""
    # from engine.core.lang_lexicons import format_lexicon_prompt
    try:
        format_lexicon_prompt(lang)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK
