#!/usr/bin/env python3
"""Property-based tests for cube_providers.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, r'C:\\Users\\ludov\\MUNINN-\\engine\\core')

from hypothesis import given, strategies as st, settings
from engine.core.cube_providers import *

@given(cube=st.text(max_size=50), neighbors=st.text(max_size=50), provider=st.text(max_size=50), ncd_threshold=st.floats(allow_nan=False, allow_infinity=False), ast_hints=st.text(max_size=50))
@settings(max_examples=50)
def test_reconstruct_cube_no_crash(cube, neighbors, provider, ncd_threshold, ast_hints):
    """Smoke: reconstruct_cube() does not crash on arbitrary input"""
    # from engine.core.cube_providers import reconstruct_cube
    try:
        reconstruct_cube(cube, neighbors, provider, ncd_threshold, ast_hints)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(original=st.text(max_size=100), reconstruction=st.text(max_size=100))
@settings(max_examples=50)
def test_validate_reconstruction_no_crash(original, reconstruction):
    """Smoke: validate_reconstruction() does not crash on arbitrary input"""
    # from engine.core.cube_providers import validate_reconstruction
    try:
        validate_reconstruction(original, reconstruction)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(cube=st.text(max_size=50), neighbors=st.text(max_size=50), provider=st.text(max_size=50))
@settings(max_examples=50)
def test_compute_hotness_no_crash(cube, neighbors, provider):
    """Smoke: compute_hotness() does not crash on arbitrary input"""
    # from engine.core.cube_providers import compute_hotness
    try:
        compute_hotness(cube, neighbors, provider)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(a=st.text(max_size=100), b=st.text(max_size=100))
@settings(max_examples=50)
def test_compute_ncd_no_crash(a, b):
    """Smoke: compute_ncd() does not crash on arbitrary input"""
    # from engine.core.cube_providers import compute_ncd
    try:
        compute_ncd(a, b)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK
