#!/usr/bin/env python3
"""Property-based tests for ai_router.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest
from hypothesis import given, strategies as st, settings
from muninn.ui.ai_router import *


# cwd guard: the destructive detector catches direct mkdir/write/open
# calls in fuzzed function bodies, but it does not follow indirect calls
# (e.g. parse_input() -> IndexBuilder() -> mkdir()). When Hypothesis fuzzes
# a path-like arg with a random string like '0' or '\xfeQ', the indirect
# mkdir resolves it relative to cwd and pollutes the repo root.
# This autouse fixture chdir's into tmp_path before each test, so any
# indirect file-system mutation lands in a sandbox pytest cleans up.
@pytest.fixture(autouse=True)
def _forge_isolate_cwd(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

@given(base_url=st.text(max_size=100))
@settings(max_examples=50)
def test_get_available_models_no_crash(base_url):
    """Smoke: get_available_models() does not crash on arbitrary input"""
    # from muninn.ui.ai_router import get_available_models
    try:
        get_available_models(base_url)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(text=st.text(max_size=100), base_url=st.text(max_size=100))
@settings(max_examples=50)
def test_pick_model_no_crash(text, base_url):
    """Smoke: pick_model() does not crash on arbitrary input"""
    # from muninn.ui.ai_router import pick_model
    try:
        pick_model(text, base_url)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(model=st.text(max_size=100))
@settings(max_examples=50)
def test_get_route_label_no_crash(model):
    """Smoke: get_route_label() does not crash on arbitrary input"""
    # from muninn.ui.ai_router import get_route_label
    try:
        get_route_label(model)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK
