#!/usr/bin/env python3
"""Property-based tests for muninn_layers.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'engine/core'))

from hypothesis import given, strategies as st, settings
from engine.core.muninn_layers import *
# BUG-102 (forge): the following functions were SKIPPED because
# they have side effects (write to disk, run subprocess, hit
# network). Fuzzing them without isolation would corrupt the repo.
# To test them, write isolated tests by hand using tmp_path.
#   - compress_line  (calls .replace())
#   - extract_facts  (calls .replace())
#   - compress_file  (name matches /^compress_file/)
#   - decode_line  (calls .replace())
#   - verify_compression  (path arg + .read_text())


@given(repo_path=st.text(max_size=50))
@settings(max_examples=50)
def test_load_codebook_no_crash(repo_path):
    """Smoke: load_codebook() does not crash on arbitrary input"""
    # from engine.core.muninn_layers import load_codebook
    try:
        load_codebook(repo_path)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(line=st.text(max_size=100))
@settings(max_examples=50)
def test_tag_memory_type_no_crash(line):
    """Smoke: tag_memory_type() does not crash on arbitrary input"""
    # from engine.core.muninn_layers import tag_memory_type
    try:
        tag_memory_type(line)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(header=st.text(max_size=100), lines=st.text(max_size=50))
@settings(max_examples=50)
def test_compress_section_no_crash(header, lines):
    """Smoke: compress_section() does not crash on arbitrary input"""
    # from engine.core.muninn_layers import compress_section
    try:
        compress_section(header, lines)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK
