#!/usr/bin/env python3
"""Property-based tests for propagation.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest
from hypothesis import given, strategies as st, settings
from engine.core.scanner.propagation import *


# cwd guard: the destructive detector catches direct mkdir/write/open
# calls in fuzzed function bodies, but it does not follow indirect calls
# (e.g. parse_input() -> IndexBuilder() -> mkdir()). When Hypothesis fuzzes
# a path-like arg with a random string like '0' or '\xfeQ', the indirect
# mkdir resolves it relative to cwd and pollutes the repo root.
# This autouse fixture chdir's into tmp_path before each test, so any
# indirect file-system mutation lands in a sandbox pytest cleans up.
@pytest.fixture(autouse=True)
def _forge_isolate_cwd(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

@given(graph=st.text(max_size=50), infected_files=st.text(max_size=50), importance=st.text(max_size=50), max_rounds=st.integers(-1000, 1000))
@settings(max_examples=50)
def test_debtrank_no_crash(graph, infected_files, importance, max_rounds):
    """Smoke: debtrank() does not crash on arbitrary input"""
    # from engine.core.scanner.propagation import debtrank
    try:
        debtrank(graph, infected_files, importance, max_rounds)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(graph=st.text(max_size=50), infected_files=st.text(max_size=50), laplacian=st.text(max_size=50), t=st.floats(allow_nan=False, allow_infinity=False))
@settings(max_examples=50)
def test_heat_kernel_no_crash(graph, infected_files, laplacian, t):
    """Smoke: heat_kernel() does not crash on arbitrary input"""
    # from engine.core.scanner.propagation import heat_kernel
    try:
        heat_kernel(graph, infected_files, laplacian, t)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(file_metrics=st.text(max_size=50))
@settings(max_examples=50)
def test_compute_importance_no_crash(file_metrics):
    """Smoke: compute_importance() does not crash on arbitrary input"""
    # from engine.core.scanner.propagation import compute_importance
    try:
        compute_importance(file_metrics)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(findings=st.text(max_size=50), blast_radii=st.text(max_size=50))
@settings(max_examples=50)
def test_competing_epidemics_order_no_crash(findings, blast_radii):
    """Smoke: competing_epidemics_order() does not crash on arbitrary input"""
    # from engine.core.scanner.propagation import competing_epidemics_order
    try:
        competing_epidemics_order(findings, blast_radii)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(graph=st.text(max_size=50), file_metrics=st.text(max_size=50), k=st.integers(-1000, 1000), method=st.text(max_size=100))
@settings(max_examples=50)
def test_influence_minimization_no_crash(graph, file_metrics, k, method):
    """Smoke: influence_minimization() does not crash on arbitrary input"""
    # from engine.core.scanner.propagation import influence_minimization
    try:
        influence_minimization(graph, file_metrics, k, method)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(findings=st.text(max_size=50), graph=st.text(max_size=50), file_metrics=st.text(max_size=50), method=st.text(max_size=100))
@settings(max_examples=50)
def test_propagate_findings_no_crash(findings, graph, file_metrics, method):
    """Smoke: propagate_findings() does not crash on arbitrary input"""
    # from engine.core.scanner.propagation import propagate_findings
    try:
        propagate_findings(findings, graph, file_metrics, method)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK
