"""CHUNK D6 — .gitattributes routes future binary commits through LFS.

CHUNK H4 (2026-05-08): hardened from regex/grep to a real parser.
.gitattributes has a well-defined grammar (one rule per non-comment
line: <pattern> <attr> <attr> ...). We parse it into a list of
(pattern, attrs_set) tuples and assert structurally — a reformat that
keeps semantic identity (e.g. add a tab vs spaces, reorder attrs)
no longer breaks the suite.

Source: docs/CHUNKS_AUDIT2_FIX_LIST_2026-05-08.md §D6
        docs/BATTLE_PLAN_AUDIT3_2026-05-08.md §H4
"""
from pathlib import Path

import pytest


REPO = Path(__file__).resolve().parent.parent
GA = REPO / ".gitattributes"


def _parse_gitattributes(text: str) -> list[tuple[str, set[str]]]:
    """Parse .gitattributes into [(pattern, {attrs}), ...].

    .gitattributes line format (per `man gitattributes`):
        <pattern>   <attr1> <attr2> ...
    Comments start with '#'. Blank lines ignored.
    """
    rules: list[tuple[str, set[str]]] = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split()
        if len(parts) < 2:
            # A pattern alone (no attrs) is technically valid but we
            # require attrs for our use case.
            continue
        pattern = parts[0]
        attrs = set(parts[1:])
        rules.append((pattern, attrs))
    return rules


def _attrs_for(rules: list[tuple[str, set[str]]], pattern: str) -> set[str]:
    """Return the merged attribute set for `pattern` (or empty set)."""
    out: set[str] = set()
    for p, attrs in rules:
        if p == pattern:
            out |= attrs
    return out


@pytest.fixture(scope="module")
def rules():
    if not GA.exists():
        pytest.skip(".gitattributes not present")
    return _parse_gitattributes(GA.read_text(encoding="utf-8"))


def test_gitattributes_exists():
    assert GA.exists(), ".gitattributes missing — see CHUNK D6"


def test_gitattributes_parses_to_at_least_5_rules(rules):
    """Sanity: the file must contain at least the documented rules."""
    assert len(rules) >= 5, (
        f"Expected ≥5 attribute rules, got {len(rules)}. "
        f"Rules: {rules!r}"
    )


def test_png_routed_to_lfs(rules):
    """*.png must declare lfs filter + diff + merge handlers."""
    attrs = _attrs_for(rules, "*.png")
    assert "filter=lfs" in attrs, (
        f"*.png missing filter=lfs (got attrs: {attrs})"
    )
    assert "diff=lfs" in attrs, "*.png missing diff=lfs"
    assert "merge=lfs" in attrs, "*.png missing merge=lfs"
    assert "-text" in attrs, (
        "*.png must declare -text (binary marker for LFS)"
    )


def test_db_routed_to_lfs(rules):
    attrs = _attrs_for(rules, "*.db")
    assert "filter=lfs" in attrs, ".db missing filter=lfs"
    assert "-text" in attrs, ".db must declare -text"


def test_python_files_text_with_lf_eol(rules):
    """*.py must be marked text + LF eol so cross-platform diffs work."""
    attrs = _attrs_for(rules, "*.py")
    assert "text" in attrs, f"*.py must declare text (got: {attrs})"
    assert "eol=lf" in attrs, f"*.py must declare eol=lf (got: {attrs})"


def test_constraints_txt_marked_generated(rules):
    """constraints.txt is an autogenerated lockfile — should be tagged
    so GitHub linguist excludes it from language stats."""
    attrs = _attrs_for(rules, "constraints.txt")
    assert "linguist-generated=true" in attrs, (
        f"constraints.txt missing linguist-generated=true tag "
        f"(got: {attrs})"
    )


def test_no_duplicate_pattern_with_conflicting_attrs(rules):
    """A pattern should not appear twice with conflicting attrs (e.g.
    `*.py text` AND `*.py binary`). Catches accidental dupes."""
    seen: dict[str, set[str]] = {}
    for pattern, attrs in rules:
        if pattern in seen:
            # Conflicting if one says `text` and another `-text`/`binary`
            combined = seen[pattern] | attrs
            if "text" in combined and ("-text" in combined or "binary" in combined):
                pytest.fail(
                    f"Pattern {pattern!r} has conflicting attributes: "
                    f"{seen[pattern]} vs {attrs}"
                )
            seen[pattern] |= attrs
        else:
            seen[pattern] = set(attrs)
