#!/usr/bin/env python3
"""Property-based tests for sentiment.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'engine/core'))

import pytest
from hypothesis import given, strategies as st, settings
from engine.core.sentiment import *


# BUG-102 cwd guard (added 2026-05-07): the destructive detector
# catches direct mkdir/write/open calls in fuzzed function bodies,
# but it does not follow indirect calls (e.g. extract_tags() ->
# Mycelium() -> mkdir()). When Hypothesis fuzzes a path-like arg
# with a random string like '0' or '\xfeQ', the indirect mkdir
# resolves it relative to cwd and pollutes the repo root.
# This autouse fixture chdir's into a tmp_path before each test,
# so any indirect file-system mutation lands in a sandbox that
# pytest cleans up automatically.
@pytest.fixture(autouse=True)
def _forge_isolate_cwd(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

@given(text=st.text(max_size=100))
@settings(max_examples=50)
def test_score_sentiment_no_crash(text):
    """Smoke: score_sentiment() does not crash on arbitrary input"""
    # from engine.core.sentiment import score_sentiment
    try:
        score_sentiment(text)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(messages=st.text(max_size=50))
@settings(max_examples=50)
def test_score_session_no_crash(messages):
    """Smoke: score_session() does not crash on arbitrary input"""
    # from engine.core.sentiment import score_session
    try:
        score_session(messages)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(valence=st.floats(allow_nan=False, allow_infinity=False), arousal=st.floats(allow_nan=False, allow_infinity=False))
@settings(max_examples=50)
def test_circumplex_map_no_crash(valence, arousal):
    """Smoke: circumplex_map() does not crash on arbitrary input"""
    # from engine.core.sentiment import circumplex_map
    try:
        circumplex_map(valence, arousal)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK
