#!/usr/bin/env python3
"""Property-based tests for lexicons.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from hypothesis import given, strategies as st, settings
from engine.core.lexicons import *

@given(tier=st.text(max_size=100))
@settings(max_examples=50)
def test_get_safe_filler_patterns_no_crash(tier):
    """Smoke: get_safe_filler_patterns() does not crash on arbitrary input"""
    # from engine.core.lexicons import get_safe_filler_patterns
    try:
        get_safe_filler_patterns(tier)
    except (ValueError, TypeError, KeyError, IndexError):
        pass  # Expected rejections are OK
