#!/usr/bin/env python3
"""Property-based tests for muninn_feed.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, r'C:\\Users\\ludov\\MUNINN-\\engine\\core')

from hypothesis import given, strategies as st, settings
from engine.core.muninn_feed import *
# BUG-102 (forge): the following functions were SKIPPED because
# they have side effects (write to disk, run subprocess, hit
# network). Fuzzing them without isolation would corrupt the repo.
# To test them, write isolated tests by hand using tmp_path.
#   - feed_from_transcript  (name matches /^feed/)
#   - compress_transcript  (calls .mkdir())
#   - feed_from_hook  (name matches /^feed/)
#   - feed_from_stop_hook  (name matches /^feed/)
#   - feed_history  (name matches /^feed/)
#   - feed_watch  (name matches /^feed/)
#   - ingest  (name matches /^ingest/)
#   - touch_heartbeat  (calls .write_text())


@given(jsonl_path=st.text(max_size=50))
@settings(max_examples=50)
def test_parse_transcript_no_crash(jsonl_path):
    """Smoke: parse_transcript() does not crash on arbitrary input"""
    # from engine.core.muninn_feed import parse_transcript
    try:
        parse_transcript(jsonl_path)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK
