#!/usr/bin/env python3
"""Property-based tests for forge_metrics.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest
from hypothesis import given, strategies as st, settings
from engine.core.forge_metrics import *


# cwd guard: the destructive detector catches direct mkdir/write/open
# calls in fuzzed function bodies, but it does not follow indirect calls
# (e.g. parse_input() -> IndexBuilder() -> mkdir()). When Hypothesis fuzzes
# a path-like arg with a random string like '0' or '\xfeQ', the indirect
# mkdir resolves it relative to cwd and pollutes the repo root.
# This autouse fixture chdir's into tmp_path before each test, so any
# indirect file-system mutation lands in a sandbox pytest cleans up.
@pytest.fixture(autouse=True)
def _forge_isolate_cwd(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

@given(repo=st.text(max_size=50))
@settings(max_examples=50, deadline=None)  # shells out to `forge`, slow
def test_get_repo_risk_no_crash(repo):
    """Smoke: get_repo_risk() does not crash on arbitrary input"""
    # from engine.core.forge_metrics import get_repo_risk
    try:
        get_repo_risk(repo)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(score=st.floats(allow_nan=False, allow_infinity=False))
@settings(max_examples=50)
def test_color_for_score_no_crash(score):
    """Smoke: color_for_score() does not crash on arbitrary input"""
    # from engine.core.forge_metrics import color_for_score
    try:
        color_for_score(score)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(repo=st.text(max_size=50), file_path=st.text(max_size=100))
@settings(max_examples=50, deadline=None)  # shells out to `forge`, slow
def test_forge_score_for_path_no_crash(repo, file_path):
    """Smoke: forge_score_for_path() does not crash on arbitrary input"""
    # from engine.core.forge_metrics import forge_score_for_path
    try:
        forge_score_for_path(repo, file_path)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK

@given(repo=st.text(max_size=50), file_path=st.text(max_size=100), default=st.text(max_size=100))
@settings(max_examples=50, deadline=None)  # shells out to `forge`, slow
def test_forge_color_for_path_no_crash(repo, file_path, default):
    """Smoke: forge_color_for_path() does not crash on arbitrary input"""
    # from engine.core.forge_metrics import forge_color_for_path
    try:
        forge_color_for_path(repo, file_path, default)
    except (ValueError, TypeError, KeyError, IndexError,
            OSError, AttributeError, RuntimeError, SyntaxError,
            LookupError, ArithmeticError, AssertionError,
            SystemExit, Exception):
        pass  # Expected rejections are OK
