#!/usr/bin/env python3
"""Property-based tests for _secrets.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'engine/core'))

import pytest
from hypothesis import given, strategies as st, settings
from engine.core._secrets import *


# BUG-102 cwd guard (added 2026-05-07): the destructive detector
# catches direct mkdir/write/open calls in fuzzed function bodies,
# but it does not follow indirect calls (e.g. extract_tags() ->
# Mycelium() -> mkdir()). When Hypothesis fuzzes a path-like arg
# with a random string like '0' or '\xfeQ', the indirect mkdir
# resolves it relative to cwd and pollutes the repo root.
# This autouse fixture chdir's into a tmp_path before each test,
# so any indirect file-system mutation lands in a sandbox that
# pytest cleans up automatically.
@pytest.fixture(autouse=True)
def _forge_isolate_cwd(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)

@given(text=st.text(max_size=100))
@settings(max_examples=50)
def test_redact_secrets_text_no_crash(text):
    """Smoke: redact_secrets_text() does not crash on arbitrary input"""
    # from engine.core._secrets import redact_secrets_text
    try:
        redact_secrets_text(text)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(text=st.text(max_size=100))
@settings(max_examples=50)
def test_count_chained_commands_no_crash(text):
    """Smoke: count_chained_commands() does not crash on arbitrary input"""
    # from engine.core._secrets import count_chained_commands
    try:
        count_chained_commands(text)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(text=st.text(max_size=100), max_chains=st.integers(-1000, 1000))
@settings(max_examples=50)
def test_clamp_chained_commands_no_crash(text, max_chains):
    """Smoke: clamp_chained_commands() does not crash on arbitrary input"""
    # from engine.core._secrets import clamp_chained_commands
    try:
        clamp_chained_commands(text, max_chains)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK
