#!/usr/bin/env python3
"""Property-based tests for lang_lexicons.py — generated by forge.py --gen-props"""
import sys
import os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'engine\\core'))

from hypothesis import given, strategies as st, settings
from engine.core.lang_lexicons import *

@given(lang=st.text(max_size=100))
@settings(max_examples=50)
def test_get_lexicon_no_crash(lang):
    """Smoke: get_lexicon() does not crash on arbitrary input"""
    # from engine.core.lang_lexicons import get_lexicon
    try:
        get_lexicon(lang)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK

@given(lang=st.text(max_size=100))
@settings(max_examples=50)
def test_format_lexicon_prompt_no_crash(lang):
    """Smoke: format_lexicon_prompt() does not crash on arbitrary input"""
    # from engine.core.lang_lexicons import format_lexicon_prompt
    try:
        format_lexicon_prompt(lang)
    except (ValueError, TypeError, KeyError, IndexError, OSError, AttributeError, RuntimeError, SystemExit):
        pass  # Expected rejections are OK
