#!/usr/bin/env python3
"""Muninn install/hooks/cron — extracted from muninn.py during chunk C.1 split.

Owns:
  - repo registry helpers (_repos_registry_path, _load_repos_registry,
    _register_repo) — registers repos in ~/.muninn/repos.json for P20c
    cross-repo discovery.
  - hook generators (_generate_bridge_hook, _generate_post_tool_failure_hook,
    _generate_subagent_start_hook, _generate_session_start_hook) — write
    .claude/hooks/*.py files into the target repo.
  - PreToolUse / scaling hook installers (_install_pre_tool_use_hooks,
    _install_scaling_hooks, _copy_hooks_from_source).
  - install_hooks orchestrator — wires .claude/settings.local.json.
  - install_cron + _detect_init_system — systemd-user timer for weekly
    `muninn-mem prune`.

This module is read-only of muninn package globals via `import muninn as _m`
inside function bodies (anti-circular). Top-level imports stay minimal.

Chunk C.1 of docs/BATTLE_PLAN_MASTER_MCP.md (2026-05-11 nuit). Moved out of
engine/core/muninn.py to keep that file under the 2500L cap (test_brick20).
"""
from __future__ import annotations

import json
import os
import re
import sys
import time
from pathlib import Path

# Shared with muninn.py and muninn_secrets.py — single source of truth.
try:
    from _secrets import secure_perms
except ImportError:  # pragma: no cover
    from engine.core._secrets import secure_perms


def _repos_registry_path() -> Path:
    """Path to the shared repos registry (~/.muninn/repos.json)."""
    return Path.home() / ".muninn" / "repos.json"


def _load_repos_registry() -> dict:
    """Load the repos registry. Returns {repo_name: absolute_path_str, ...}."""
    reg_path = _repos_registry_path()
    if not reg_path.exists():
        return {}
    try:
        data = json.loads(reg_path.read_text(encoding="utf-8"))
        return data.get("repos", {})
    except (json.JSONDecodeError, OSError):
        return {}


def _register_repo(repo_path: Path):
    """Register a repo in ~/.muninn/repos.json for P20c cross-repo discovery."""
    repo_path = repo_path.resolve()
    reg_path = _repos_registry_path()
    reg_path.parent.mkdir(parents=True, exist_ok=True)

    registry = {}
    if reg_path.exists():
        try:
            registry = json.loads(reg_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            registry = {}

    repos = registry.get("repos", {})
    repo_key = repo_path.name
    repo_str = str(repo_path)

    if repos.get(repo_key) == repo_str:
        return  # Already registered with same path

    repos[repo_key] = repo_str
    registry["repos"] = repos
    registry["updated"] = time.strftime("%Y-%m-%d %H:%M:%S")
    # Atomic write to prevent concurrent hook corruption
    import tempfile
    fd, tmp = tempfile.mkstemp(dir=str(reg_path.parent), suffix=".tmp")
    fd_closed = False
    try:
        os.write(fd, json.dumps(registry, indent=2, ensure_ascii=False).encode("utf-8"))
        os.close(fd)
        fd_closed = True
        os.replace(tmp, str(reg_path))
    except Exception:
        if not fd_closed:
            try:
                os.close(fd)
            except OSError:
                pass
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    print(f"  Repo registered: {repo_key}")
def _generate_bridge_hook(repo_path: Path, engine_core_dir: Path) -> Path:
    """Generate a bridge_hook.py in the target repo's .claude/hooks/ directory.

    The generated hook points to the correct engine/core path regardless of
    where the repo lives. Returns the path to the generated file.
    """
    hooks_dir = repo_path / ".claude" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    bridge_path = hooks_dir / "bridge_hook.py"

    bridge_code = f'''#!/usr/bin/env python3
"""P42 UserPromptSubmit hook — Live Mycelium Bridge + Secret Sentinel.

Reads user prompt from stdin (JSON), checks for accidental secrets,
then runs bridge_fast() for activated concepts.

Auto-generated by muninn install_hooks(). Do not edit manually.
Target: <0.5s total execution time.
"""
import json
import math
import re
import sys
import os
from pathlib import Path

def _shannon_entropy(s):
    """Shannon entropy of a string. High entropy = likely a secret."""
    if not s:
        return 0.0
    freq = {{}}
    for c in s:
        freq[c] = freq.get(c, 0) + 1
    length = len(s)
    return -sum((n / length) * math.log2(n / length) for n in freq.values())

def _has_char_diversity(s):
    """Check if string has mixed character classes (upper+lower+digit+special)."""
    classes = 0
    if re.search(r'[a-z]', s): classes += 1
    if re.search(r'[A-Z]', s): classes += 1
    if re.search(r'[0-9]', s): classes += 1
    if re.search(r'[^a-zA-Z0-9\\s]', s): classes += 1
    return classes >= 3

_SECRET_TRIGGERS = re.compile(
    r'(?:cl[eé]|key|password|mdp|mot de passe|passwd|secret|token|passphrase'
    r'|api.?key|credentials?|auth)',
    re.IGNORECASE
)

def _check_secrets(prompt):
    """Detect if user accidentally typed a password/key in their prompt.
    Returns warning string or None."""
    # 1. Check known API key patterns (structural)
    _API_PATTERNS = [
        r'ghp_[A-Za-z0-9]{{20,}}', r'sk-[A-Za-z0-9\\-._]{{20,}}',
        r'AKIA[A-Z0-9]{{16}}', r'Bearer\\s+[A-Za-z0-9\\-._~+/]+=*',
    ]
    for pat in _API_PATTERNS:
        if re.search(pat, prompt):
            return "[MUNINN SENTINEL] API key/token detected in your message. It will be stored in the Claude transcript. Consider rotating it."

    # 2. Check for password-like strings near trigger words
    if _SECRET_TRIGGERS.search(prompt):
        words = prompt.split()
        for word in words:
            clean = word.strip('.,;:!?\\'\\"/()[]{{}}')
            if len(clean) >= 6 and _has_char_diversity(clean) and _shannon_entropy(clean) > 2.8:
                return "[MUNINN SENTINEL] You may have typed a password or secret in your message. It will be recorded in the Claude transcript (.jsonl). Consider changing it. Muninn will redact it from .mn files but CANNOT erase it from the raw transcript."

    # 3. Standalone high-entropy check (no trigger needed) for very suspicious strings
    for word in prompt.split():
        clean = word.strip('.,;:!?\\'\\"/()[]{{}}')
        if len(clean) >= 10 and _has_char_diversity(clean) and _shannon_entropy(clean) > 3.5:
            return "[MUNINN SENTINEL] High-entropy string detected — possible password or key. It will be stored in the raw transcript."

    return None

def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
        hook_input = json.loads(raw)
    except (json.JSONDecodeError, UnicodeDecodeError, ValueError, OSError):
        sys.exit(0)

    # Audit 2026-04-10: type-check before .get() to never crash on bad input
    if not isinstance(hook_input, dict):
        sys.exit(0)

    prompt = hook_input.get("prompt", "")
    if not prompt or not isinstance(prompt, str) or len(prompt) < 10:
        sys.exit(0)

    # Secret detection — runs FIRST, before anything else
    warning = _check_secrets(prompt)
    if warning:
        print(warning)
        sys.stdout.flush()

    repo_path = hook_input.get("cwd", os.getcwd())

    # Source-tree fallback: add engine/core to sys.path if present.
    # Pip-installed mode: import muninn resolves via site-packages.
    engine_core = Path(__file__).resolve().parent.parent.parent / "engine" / "core"
    if engine_core.exists() and str(engine_core) not in sys.path:
        sys.path.insert(0, str(engine_core))

    try:
        import muninn
        muninn._REPO_PATH = Path(repo_path).resolve()
        muninn._refresh_tree_paths()
        result = muninn.bridge_fast(prompt)
        if result:
            # Anti-Adversa clamp (chunk 3 of leak intel battle plan).
            # Refuse injection of any content with >30 chained shell commands.
            # See docs/CLAUDE_CODE_LEAK_INTEL.md section 10.
            try:
                from _secrets import clamp_chained_commands
                result, _ = clamp_chained_commands(result)
            except Exception:
                pass  # never block hook execution on a defense failure
            print(result)
    except Exception as e:
        print(f"[MUNINN BRIDGE ERROR] {{type(e).__name__}}: {{e}}", file=sys.stderr)

    sys.exit(0)


if __name__ == "__main__":
    main()
'''
    bridge_path.write_text(bridge_code, encoding="utf-8")
    secure_perms(bridge_path, mode=0o700)  # hook script — owner-only execute
    return bridge_path


def _generate_post_tool_failure_hook(repo_path: Path, engine_core_dir: Path) -> Path:
    """Generate post_tool_failure_hook.py in the target repo's .claude/hooks/.

    Chunk 4 of leak intel battle plan: PostToolUseFailure hook auto-feeds
    .muninn/errors.json with structured tool failure entries (Claude Code's
    25+ hook system surfaces this in real time, replacing the older
    transcript-scraping P18 path).

    The generated hook is self-contained — no engine import needed. It writes
    directly to .muninn/errors.json in the same P18 schema (error/fix/date).
    See docs/CLAUDE_CODE_LEAK_INTEL.md sections 4 + 12.
    """
    hooks_dir = repo_path / ".claude" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    ptf_path = hooks_dir / "post_tool_failure_hook.py"

    ptf_code = '''#!/usr/bin/env python3
"""PostToolUseFailure hook — auto-feed errors.json from real-time tool failures.

Reads PostToolUseFailure JSON payload from stdin (Claude Code spec).
Appends a new entry to .muninn/errors.json in P18 schema:
  {"error": "<tool> | <summary>", "fix": "", "date": "YYYY-MM-DD"}

Design:
- NEVER raise (always exit 0). Hook failure must not block Claude.
- NEVER write to stdout (PostToolUseFailure is non-blocking, would be lost).
- Atomic write via tempfile + os.replace.
- Dedup: skip if last entry has identical (error, date).
- Cap errors.json at 500 entries (drop oldest first).

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import sys
import tempfile
from datetime import datetime
from pathlib import Path

MAX_ENTRIES = 500


def _safe_summary(tool_name, error, max_len=200):
    if not error:
        error = "(no error message)"
    first = error.splitlines()[0] if error else ""
    summary = f"{tool_name} | {first}"
    if len(summary) > max_len:
        summary = summary[: max_len - 3] + "..."
    return summary


def _load_existing(errors_path):
    if not errors_path.exists():
        return []
    try:
        data = json.loads(errors_path.read_text(encoding="utf-8"))
        if isinstance(data, list):
            return data
        return []
    except Exception:
        return []


def _atomic_write(errors_path, data):
    errors_path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(
        dir=str(errors_path.parent), suffix=".tmp", prefix=".errors-"
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
        os.replace(tmp, str(errors_path))
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass


def feed_errors_json(payload, repo_path):
    if not isinstance(payload, dict):
        return False
    tool_name = payload.get("tool_name", "")
    error_msg = payload.get("error", "")
    if not tool_name and not error_msg:
        return False

    errors_path = Path(repo_path) / ".muninn" / "errors.json"
    existing = _load_existing(errors_path)

    summary = _safe_summary(tool_name, error_msg)
    today = datetime.now().strftime("%Y-%m-%d")
    entry = {"error": summary, "fix": "", "date": today}

    if existing and isinstance(existing[-1], dict):
        last = existing[-1]
        if last.get("error") == summary and last.get("date") == today:
            return False

    existing.append(entry)

    if len(existing) > MAX_ENTRIES:
        existing = existing[-MAX_ENTRIES:]

    _atomic_write(errors_path, existing)
    return True


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
        payload = json.loads(raw)
    except Exception:
        sys.exit(0)

    # Audit 2026-04-10: type-check before .get() to never crash on bad input
    if not isinstance(payload, dict):
        sys.exit(0)

    repo_path = payload.get("cwd") or os.getcwd()

    try:
        feed_errors_json(payload, Path(repo_path))
    except Exception:
        pass

    sys.exit(0)


if __name__ == "__main__":
    main()
'''
    ptf_path.write_text(ptf_code, encoding="utf-8")
    secure_perms(ptf_path, mode=0o700)  # hook script — owner-only execute
    return ptf_path


def _generate_subagent_start_hook(repo_path: Path, engine_core_dir: Path) -> Path:
    """Generate subagent_start_hook.py in the target repo's .claude/hooks/.

    Chunk 5 of leak intel battle plan: SubagentStart hook injects a Muninn
    boot slice into spawned sub-agents (Explore, Plan, custom). Without it,
    sub-agents start with empty Muninn context.

    See docs/CLAUDE_CODE_LEAK_INTEL.md sections 4 + 12.
    """
    hooks_dir = repo_path / ".claude" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    sas_path = hooks_dir / "subagent_start_hook.py"

    sas_code = '''#!/usr/bin/env python3
"""SubagentStart hook — inject a LIGHT Muninn slice into spawned sub-agents.

Reads SubagentStart payload from stdin (Claude Code spec).

LIGHT MODE: instead of calling muninn.boot() (which runs spreading activation,
L10 cue distillation, KIComp filtering and takes 100+ seconds on large trees),
we directly read root.mn from disk and at most 1 branch that name-matches
the agent_type. Target: <500ms.

Design rules:
- Pure file I/O. No engine import, no mycelium queries, no spreading.
- Cap output hard.
- Never raise (exit 0 always).
- On any failure, emit empty additionalContext (fail-safe).

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import sys
from pathlib import Path

MAX_INJECT_CHARS = 20000  # ~5000 tokens


def _emit_empty():
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "SubagentStart",
            "additionalContext": "",
        }
    }))
    sys.exit(0)


def _truncate_with_marker(text, max_chars):
    # BUG-101 fix (audit 2026-04-10): clamp negative slice and account for
    # marker length, otherwise small max_chars produces oversized output.
    if max_chars <= 0:
        return ""
    if len(text) <= max_chars:
        return text
    marker = "\\n\\n[... Muninn slice truncated to fit sub-agent context ...]"
    if max_chars <= len(marker):
        return marker[:max_chars]
    slice_end = max(0, max_chars - len(marker))
    return text[:slice_end] + marker


def _find_tree_dir(repo_path):
    candidates = [
        repo_path / ".muninn" / "tree",
        repo_path / "memory",
    ]
    for c in candidates:
        if c.exists() and c.is_dir():
            return c
    return None


def _read_root(tree_dir):
    root_file = tree_dir / "root.mn"
    if not root_file.exists():
        return ""
    try:
        return root_file.read_text(encoding="utf-8")
    except OSError:
        return ""


def _find_relevant_branch(tree_dir, agent_type):
    if not agent_type:
        return "", ""
    keyword = agent_type.lower()
    for branch_file in sorted(tree_dir.glob("*.mn")):
        if branch_file.name == "root.mn":
            continue
        if keyword in branch_file.stem.lower():
            try:
                return branch_file.stem, branch_file.read_text(encoding="utf-8")
            except OSError:
                continue
    for branch_file in sorted(tree_dir.glob("*.mn")):
        if branch_file.name == "root.mn":
            continue
        try:
            head = branch_file.read_text(encoding="utf-8")[:500]
            if keyword in head.lower():
                return branch_file.stem, branch_file.read_text(encoding="utf-8")
        except OSError:
            continue
    return "", ""


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
        payload = json.loads(raw)
    except Exception:
        _emit_empty()
        return

    if not isinstance(payload, dict):
        _emit_empty()
        return

    agent_type = payload.get("agent_type", "")
    repo_path_str = payload.get("cwd") or os.getcwd()
    repo_path = Path(repo_path_str).resolve()

    tree_dir = _find_tree_dir(repo_path)
    if tree_dir is None:
        _emit_empty()
        return

    try:
        root_text = _read_root(tree_dir)
        branch_name, branch_text = _find_relevant_branch(tree_dir, agent_type)

        parts = []
        parts.append(
            f"[MUNINN LIGHT BOOT for {agent_type or 'subagent'}]\\n"
            f"You are a sub-agent with read access to Sky's Muninn memory tree "
            f"at {repo_path}.\\n"
            f"This is a LIGHT slice (root + 1 branch). For more context, read "
            f".muninn/tree/ or memory/ directly.\\n"
            f"Use it as background, not as truth - verify before acting.\\n"
        )
        if root_text:
            parts.append(f"\\n=== root.mn ===\\n{root_text}")
        if branch_text:
            parts.append(f"\\n=== branch: {branch_name} ===\\n{branch_text}")

        if not root_text and not branch_text:
            _emit_empty()
            return

        injected = "\\n".join(parts)
        injected = _truncate_with_marker(injected, MAX_INJECT_CHARS)

        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "SubagentStart",
                "additionalContext": injected,
            }
        }))
    except Exception:
        _emit_empty()
        return

    sys.exit(0)


if __name__ == "__main__":
    main()
'''
    sas_path.write_text(sas_code, encoding="utf-8")
    secure_perms(sas_path, mode=0o700)  # hook script — owner-only execute
    return sas_path


def _generate_session_start_hook(repo_path: Path, engine_core_dir: Path) -> Path:
    """Generate session_start_hook.py — auto-boot Muninn at session start.

    Chunk MCP A.1 of docs/BATTLE_PLAN_MASTER_MCP.md.

    Reads SessionStart payload from stdin (Claude Code spec):
      {
        "hook_event_name": "SessionStart",
        "session_id": "...",
        "source": "startup" | "resume" | "clear" | "compact",
        "cwd": "/path/to/repo"
      }

    If source in {startup, resume}, reads .muninn/tree/root.mn + the N most
    recently modified branches (proxy for "hot"), caps to MAX_INJECT_CHARS,
    and emits as additionalContext. Claude wakes already aware of project
    memory.

    Filters out clear (fresh start) and compact (PreCompact already wrote .mn).

    LIGHT MODE design: pure file I/O. No engine import, no subprocess boot,
    no mycelium queries, no spreading activation. Same fail-safe contract
    as subagent_start_hook (exit 0 always, log errors silently).
    """
    hooks_dir = repo_path / ".claude" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)
    sss_path = hooks_dir / "session_start_hook.py"
    sss_code = '''#!/usr/bin/env python3
"""SessionStart hook — auto-boot Muninn at session start (LIGHT MODE).

Reads SessionStart payload from stdin (Claude Code spec):
  {
    "hook_event_name": "SessionStart",
    "session_id": "...",
    "source": "startup" | "resume" | "clear" | "compact",
    "cwd": "/path/to/repo"
  }

If source in {startup, resume}, reads .muninn/tree/root.mn + the N most
recently modified branches (proxy for "hot"), caps to MAX_INJECT_CHARS,
and emits as additionalContext.

Filters out clear (fresh start) and compact (PreCompact already wrote .mn).

LIGHT MODE: pure file I/O. No engine import, no subprocess, no mycelium
queries. Target: <500ms. Exit 0 always (fail-safe — must not block session).

Auto-generated by muninn install_hooks(). Do not edit manually.
"""
import json
import os
import sys
from datetime import datetime
from pathlib import Path


def _log_hook_error(context, exc):
    """Append a swallowed exception to ~/.muninn/hook_errors.log."""
    try:
        engine_core = str(Path(__file__).resolve().parent.parent.parent
                          / "engine" / "core")
        if engine_core not in sys.path:
            sys.path.insert(0, engine_core)
        from _hook_logger import log_hook_event
        log_hook_event("session_start_hook", context, exc)
    except Exception:
        try:
            sys.stderr.write(
                f"[MUNINN HOOK LOG fallback] {datetime.now().isoformat()} "
                f"[session_start_hook:{context}] {type(exc).__name__}: {exc}\\n"
            )
            sys.stderr.flush()
        except Exception:
            pass


# Main session has more context room than subagents (subagent cap = 20K),
# but we still cap defensively to avoid swamping the session window.
MAX_INJECT_CHARS = 40000  # ~10K tokens at 4 chars/token average

# Number of recently-modified branches to surface in addition to root.
TOP_RECENT_BRANCHES = 5


def _emit_empty():
    """Output an empty additionalContext, exit 0 (fail-safe)."""
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "SessionStart",
            "additionalContext": "",
        }
    }))
    sys.exit(0)


def _truncate_with_marker(text, max_chars):
    """Truncate text at max_chars, add a clear marker if truncated.

    Same BUG-101-safe pattern as subagent_start_hook: clamp slice index
    at 0 and account for the marker length when computing the slice.
    """
    if max_chars <= 0:
        return ""
    if len(text) <= max_chars:
        return text
    marker = "\\n\\n[... Muninn boot truncated to fit session context ...]"
    if max_chars <= len(marker):
        return marker[:max_chars]
    slice_end = max(0, max_chars - len(marker))
    return text[:slice_end] + marker


def _find_tree_dir(repo_path):
    """Find the .muninn/tree directory or fall back to memory/."""
    candidates = [
        repo_path / ".muninn" / "tree",
        repo_path / "memory",
    ]
    for c in candidates:
        if c.exists() and c.is_dir():
            return c
    return None


def _read_root(tree_dir):
    """Read root.mn if present."""
    root_file = tree_dir / "root.mn"
    if not root_file.exists():
        return ""
    try:
        return root_file.read_text(encoding="utf-8")
    except OSError:
        return ""


def _find_recent_branches(tree_dir, n):
    """Return up to n (name, text) tuples for the n most recently modified branches.

    "Recent" is a cheap proxy for "hot" — branches touched in the last session
    are most likely relevant when Claude wakes up. Sorted by st_mtime desc.
    """
    branches = []
    try:
        for bf in tree_dir.glob("*.mn"):
            if bf.name == "root.mn":
                continue
            try:
                branches.append((bf.stat().st_mtime, bf))
            except OSError:
                continue
    except OSError:
        return []
    branches.sort(key=lambda t: t[0], reverse=True)
    selected = []
    for _mtime, bf in branches[:n]:
        try:
            selected.append((bf.stem, bf.read_text(encoding="utf-8")))
        except OSError:
            continue
    return selected


def main():
    try:
        raw = sys.stdin.buffer.read().decode("utf-8")
    except UnicodeDecodeError as e:
        _log_hook_error("stdin_decode", e)
        _emit_empty()
        return
    except Exception as e:
        _log_hook_error("stdin_read", e)
        _emit_empty()
        return
    if not raw.strip():
        _emit_empty()
        return
    try:
        payload = json.loads(raw)
    except json.JSONDecodeError as e:
        _log_hook_error("stdin_parse", e)
        _emit_empty()
        return
    except Exception as e:
        _log_hook_error("stdin_unexpected", e)
        _emit_empty()
        return

    if not isinstance(payload, dict):
        _emit_empty()
        return

    source = payload.get("source", "")
    # Only trigger boot injection on real session starts. clear and compact
    # are no-ops here: clear is a deliberate fresh start (user wants empty
    # context), and compact already ran the PreCompact hook which wrote
    # the session .mn — re-injecting would be redundant.
    if source not in ("startup", "resume"):
        _emit_empty()
        return

    repo_path_str = payload.get("cwd") or os.getcwd()
    try:
        repo_path = Path(repo_path_str).resolve()
    except Exception as e:
        _log_hook_error("resolve_cwd", e)
        _emit_empty()
        return

    if not repo_path.exists() or not repo_path.is_dir():
        _emit_empty()
        return

    tree_dir = _find_tree_dir(repo_path)
    if tree_dir is None:
        _emit_empty()
        return

    try:
        root_text = _read_root(tree_dir)
        branches = _find_recent_branches(tree_dir, TOP_RECENT_BRANCHES)

        if not root_text and not branches:
            _emit_empty()
            return

        parts = []
        parts.append(
            f"[MUNINN SESSION BOOT - source={source}]\\n"
            f"Auto-loaded from .muninn/tree at {repo_path}.\\n"
            f"Includes root.mn + {len(branches)} recently-modified branches "
            f"(proxy for hot memory).\\n"
            f"This is memory context, not authoritative truth - verify before acting.\\n"
        )
        if root_text:
            parts.append(f"\\n=== root.mn ===\\n{root_text}")
        for bname, btext in branches:
            parts.append(f"\\n=== branch: {bname} ===\\n{btext}")

        injected = "\\n".join(parts)
        injected = _truncate_with_marker(injected, MAX_INJECT_CHARS)

        print(json.dumps({
            "hookSpecificOutput": {
                "hookEventName": "SessionStart",
                "additionalContext": injected,
            }
        }))
    except Exception as e:
        _log_hook_error("compose_injected_context", e)
        _emit_empty()
        return

    sys.exit(0)


if __name__ == "__main__":
    main()
'''
    sss_path.write_text(sss_code, encoding="utf-8")
    secure_perms(sss_path, mode=0o700)
    return sss_path


def _install_pre_tool_use_hooks(repo_path: Path) -> dict:
    """Copy the 3 PreToolUse enforcement hooks from Muninn source to target.

    Chunk 12 of leak intel battle plan: enforces RULES 1, 2, 3 in code
    rather than relying on CLAUDE.md text suggestions.

    Returns dict mapping hook script name -> destination Path.
    """
    return _copy_hooks_from_source(repo_path, [
        "pre_tool_use_bash_destructive.py",
        "pre_tool_use_bash_secrets.py",
        "pre_tool_use_edit_hardcode.py",
    ])


def _install_scaling_hooks(repo_path: Path) -> dict:
    """Copy the 3 scaling/enterprise hooks from Muninn source to target.

    Chunk 15 of leak intel battle plan: scaffolding for Phase 3 enterprise
    pitch (compliance, audit, drift detection). These hooks are COPIED to
    the target's .claude/hooks/ but NOT registered in settings.local.json.
    Sky/admin activates them manually when a customer needs them by editing
    settings.local.json.

    See docs/SCALING_NOTES.md for details.

    Returns dict mapping hook script name -> destination Path.
    """
    return _copy_hooks_from_source(repo_path, [
        "notification_audit_hook.py",
        "post_tool_use_edit_log.py",
        "config_change_hook.py",
    ])


def _copy_hooks_from_source(repo_path: Path, hook_names: list) -> dict:
    """Generic helper: copy hook scripts from this Muninn source to target.

    Source is .claude/hooks/ in the Muninn repo this code lives in.
    Target is .claude/hooks/ in repo_path.
    Skips silently if source script doesn't exist.
    """
    import shutil

    hooks_dir = repo_path / ".claude" / "hooks"
    hooks_dir.mkdir(parents=True, exist_ok=True)

    muninn_root = Path(__file__).resolve().parent.parent.parent
    source_dir = muninn_root / ".claude" / "hooks"

    installed = {}
    for name in hook_names:
        src = source_dir / name
        if not src.exists():
            continue
        dst = hooks_dir / name
        try:
            if src.resolve() == dst.resolve():
                installed[name] = dst
                continue
        except OSError:
            pass
        shutil.copyfile(src, dst)
        installed[name] = dst
    return installed


def install_hooks(repo_path: Path):
    """Install Claude Code hooks for automatic feed on PreCompact/SessionEnd/Stop/UserPromptSubmit.

    P32: Merges hook-by-hook instead of skipping when hooks key exists.
    P43: Also installs UserPromptSubmit bridge hook (generates bridge_hook.py).
    Also registers repo in ~/.muninn/repos.json for P20c cross-repo discovery.
    """
    repo_path = repo_path.resolve()
    muninn_engine = Path(__file__).resolve()
    engine_core_dir = muninn_engine.parent
    claude_dir = repo_path / ".claude"
    claude_dir.mkdir(exist_ok=True)
    settings_path = claude_dir / "settings.local.json"

    # Generate bridge_hook.py in target repo with correct engine path
    bridge_path = _generate_bridge_hook(repo_path, engine_core_dir)

    # Generate post_tool_failure_hook.py — auto-feed errors.json
    # (chunk 4 of leak intel battle plan, see CLAUDE_CODE_LEAK_INTEL.md)
    ptf_path = _generate_post_tool_failure_hook(repo_path, engine_core_dir)

    # Generate subagent_start_hook.py — inject Muninn boot into sub-agents
    # (chunk 5 of leak intel battle plan)
    sas_path = _generate_subagent_start_hook(repo_path, engine_core_dir)

    # Generate session_start_hook.py — auto-boot Muninn at session start
    # (chunk MCP A.1 of docs/BATTLE_PLAN_MASTER_MCP.md)
    sss_path = _generate_session_start_hook(repo_path, engine_core_dir)

    # Copy PreToolUse enforcement hooks (chunk 12 of leak intel battle plan)
    # These enforce CLAUDE.md RULES 1, 2, 3 in code rather than text suggestion.
    ptu_hooks = _install_pre_tool_use_hooks(repo_path)

    # Copy scaling/enterprise hooks (chunk 15) - scripts are placed in
    # target .claude/hooks/ but NOT registered in settings.local.json. Sky
    # activates them manually when a customer needs compliance/audit features.
    # See docs/SCALING_NOTES.md.
    _install_scaling_hooks(repo_path)

    # Portable command strings: use ${CLAUDE_PROJECT_DIR} (Claude Code substitutes
    # this env var at hook execution time). Two install modes:
    #   source-tree: muninn.py lives inside repo_path -> relative path under the var
    #   pip-installed: muninn is in site-packages -> use `python -m muninn`
    CPD = '${CLAUDE_PROJECT_DIR}'
    try:
        muninn_rel = muninn_engine.relative_to(repo_path).as_posix()
        feed_cmd = f'python "{CPD}/{muninn_rel}" feed --repo "{CPD}"'
        stop_cmd = f'python "{CPD}/{muninn_rel}" feed --repo "{CPD}" --trigger stop'
    except ValueError:
        feed_cmd = f'python -m muninn feed --repo "{CPD}"'
        stop_cmd = f'python -m muninn feed --repo "{CPD}" --trigger stop'

    # bridge/ptf/sas/sss scripts are always generated under repo_path/.claude/hooks/
    bridge_rel = bridge_path.relative_to(repo_path).as_posix()
    ptf_rel = ptf_path.relative_to(repo_path).as_posix()
    sas_rel = sas_path.relative_to(repo_path).as_posix()
    sss_rel = sss_path.relative_to(repo_path).as_posix()
    bridge_cmd = f'python "{CPD}/{bridge_rel}"'
    ptf_cmd = f'python "{CPD}/{ptf_rel}"'
    sas_cmd = f'python "{CPD}/{sas_rel}"'
    sss_cmd = f'python "{CPD}/{sss_rel}"'

    required_hooks = {
        "UserPromptSubmit": [{"type": "command", "command": bridge_cmd, "timeout": 5}],
        "PreCompact": [{"type": "command", "command": feed_cmd}],
        "SessionEnd": [{"type": "command", "command": feed_cmd}],
        "Stop": [{"type": "command", "command": stop_cmd}],
        "PostToolUseFailure": [{"type": "command", "command": ptf_cmd, "timeout": 5}],
        "SubagentStart": [{"type": "command", "command": sas_cmd, "timeout": 10}],
        "SessionStart": [{"type": "command", "command": sss_cmd, "timeout": 30}],
    }

    def _ptu_cmd(name: str) -> str:
        rel = Path(ptu_hooks[name]).relative_to(repo_path).as_posix()
        return f'python "{CPD}/{rel}"'

    # PreToolUse hooks use a different format with matchers
    # See https://code.claude.com/docs/en/hooks
    pre_tool_entries = []
    if "pre_tool_use_bash_destructive.py" in ptu_hooks:
        pre_tool_entries.append({
            "matcher": "Bash",
            "hooks": [{
                "type": "command",
                "command": _ptu_cmd("pre_tool_use_bash_destructive.py"),
                "timeout": 5,
            }],
        })
    if "pre_tool_use_bash_secrets.py" in ptu_hooks:
        pre_tool_entries.append({
            "matcher": "Bash",
            "hooks": [{
                "type": "command",
                "command": _ptu_cmd("pre_tool_use_bash_secrets.py"),
                "timeout": 5,
            }],
        })
    if "pre_tool_use_edit_hardcode.py" in ptu_hooks:
        pre_tool_entries.append({
            "matcher": "Edit|Write",
            "hooks": [{
                "type": "command",
                "command": _ptu_cmd("pre_tool_use_edit_hardcode.py"),
                "timeout": 5,
            }],
        })
    if pre_tool_entries:
        required_hooks["PreToolUse"] = pre_tool_entries

    # Load existing settings or start fresh
    existing = {}
    if settings_path.exists():
        try:
            existing = json.loads(settings_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, ValueError):
            existing = {}

    existing_hooks = existing.get("hooks", {})
    installed = []

    def _extract_commands(entries):
        """Extract command strings from a hook entries list, supporting both
        the simple format ({type, command}) and the matcher format
        ({matcher, hooks: [{type, command}]}) used by PreToolUse."""
        cmds = []
        for e in entries or []:
            if not isinstance(e, dict):
                continue
            if "command" in e:
                cmds.append(e.get("command", ""))
            elif "hooks" in e:
                for h in e.get("hooks", []):
                    if isinstance(h, dict):
                        cmds.append(h.get("command", ""))
        return cmds

    # Merge hook-by-hook: add missing hooks, update stale paths
    for hook_name, hook_entries in required_hooks.items():
        if hook_name not in existing_hooks:
            existing_hooks[hook_name] = hook_entries
            installed.append(hook_name)
        else:
            # Check if existing hook points to a stale muninn.py or bridge path
            existing_cmds = _extract_commands(existing_hooks[hook_name])
            new_cmds = _extract_commands(hook_entries)
            # If any existing cmd mentions muninn AND any new cmd is missing,
            # treat as needing update
            if any("muninn" in c.lower() or "pre_tool_use" in c.lower() or "bridge_hook" in c.lower()
                   or "session_start_hook" in c.lower() or "subagent_start_hook" in c.lower()
                   for c in existing_cmds):
                missing_in_existing = [nc for nc in new_cmds if nc not in existing_cmds]
                if missing_in_existing:
                    existing_hooks[hook_name] = hook_entries
                    installed.append(f"{hook_name}(updated)")

    if not installed:
        print(f"  Hooks already up-to-date (UserPromptSubmit + PreCompact + SessionEnd + Stop)")
    else:
        existing["hooks"] = existing_hooks
        # X15: Atomic write — tempfile + replace to prevent corruption
        import tempfile as _tmpmod
        tmp_fd, tmp_path = _tmpmod.mkstemp(dir=str(settings_path.parent), suffix=".tmp")
        try:
            with os.fdopen(tmp_fd, "w", encoding="utf-8") as f:
                json.dump(existing, f, indent=2, ensure_ascii=False)
            os.replace(tmp_path, str(settings_path))
        except Exception:
            try:
                os.unlink(tmp_path)
            except OSError:
                pass
            raise
        print(f"  Hooks installed: {' + '.join(installed)}")

    # Register repo in ~/.muninn/repos.json for P20c cross-repo discovery
    _register_repo(repo_path)


# ── INSTALL-CRON — weekly systemd-user timer for `muninn-mem prune` ────


def _detect_init_system() -> str:
    """Return 'systemd-user' if systemctl is on PATH, else 'none'.

    Cron fallback is not yet implemented — that's a planned A.3.bis chunk.
    """
    import shutil
    if shutil.which("systemctl") is not None:
        return "systemd-user"
    return "none"


def install_cron(repo_path: Path, uninstall: bool = False) -> dict:
    """Install (or uninstall) a systemd-user weekly timer for `muninn-mem prune`.

    Chunk MCP A.3 of docs/BATTLE_PLAN_MASTER_MCP.md.

    Generates two systemd-user units under ~/.config/systemd/user/:
      - muninn-prune.service (Type=oneshot, calls `python -m muninn prune --force`)
      - muninn-prune.timer   (OnCalendar=Sun *-*-* 04:00:00, Persistent=true)

    The function does NOT invoke systemctl — Sky runs the activation
    manually (the printed `next_action` hint shows the exact command).
    Test-friendly, sandbox-safe.

    On hosts without systemctl, returns status="skipped_no_systemd".
    Cron fallback is out-of-scope this chunk.

    Args:
        repo_path: absolute path of the Muninn repo whose mycelium to prune.
        uninstall: if True, remove the two unit files (idempotent).

    Returns:
        dict with keys: status, init_system, service_path, timer_path,
        next_action.
    """
    repo_path = Path(repo_path).resolve()
    init_system = _detect_init_system()

    home = Path(os.environ.get("HOME") or str(Path.home())).resolve()
    units_dir = home / ".config" / "systemd" / "user"
    service_path = units_dir / "muninn-prune.service"
    timer_path = units_dir / "muninn-prune.timer"

    result = {
        "status": "unknown",
        "init_system": init_system,
        "service_path": str(service_path),
        "timer_path": str(timer_path),
        "next_action": "",
    }

    if init_system != "systemd-user":
        result["status"] = "skipped_no_systemd"
        result["service_path"] = None
        result["timer_path"] = None
        return result

    if uninstall:
        for p in (service_path, timer_path):
            try:
                p.unlink()
            except FileNotFoundError:
                pass
            except OSError:
                pass
        result["status"] = "uninstalled"
        result["next_action"] = "systemctl --user daemon-reload"
        return result

    units_dir.mkdir(parents=True, exist_ok=True)
    python_bin = sys.executable or "python3"

    service_content = (
        "[Unit]\n"
        f"Description=Muninn weekly mycelium prune for {repo_path}\n"
        "Documentation=https://github.com/sky1241/MUNINN-\n"
        "After=network.target\n"
        "\n"
        "[Service]\n"
        "Type=oneshot\n"
        f"WorkingDirectory={repo_path}\n"
        "Environment=PYTHONIOENCODING=utf-8\n"
        f"ExecStart={python_bin} -m muninn prune --force --repo {repo_path}\n"
        "StandardOutput=journal\n"
        "StandardError=journal\n"
        "TimeoutStartSec=600\n"
        "Nice=10\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )

    timer_content = (
        "[Unit]\n"
        "Description=Muninn weekly prune timer (Sundays 04:00 local time)\n"
        "Documentation=https://github.com/sky1241/MUNINN-\n"
        "\n"
        "[Timer]\n"
        "OnCalendar=Sun *-*-* 04:00:00\n"
        "Persistent=true\n"
        "RandomizedDelaySec=600\n"
        "Unit=muninn-prune.service\n"
        "\n"
        "[Install]\n"
        "WantedBy=timers.target\n"
    )

    # Idempotency : if both files exist with identical content, return already_installed.
    was_present = service_path.exists() and timer_path.exists()
    if was_present:
        try:
            existing_svc = service_path.read_text(encoding="utf-8")
            existing_tmr = timer_path.read_text(encoding="utf-8")
            if existing_svc == service_content and existing_tmr == timer_content:
                result["status"] = "already_installed"
                result["next_action"] = (
                    "systemctl --user daemon-reload && "
                    "systemctl --user enable --now muninn-prune.timer"
                )
                return result
        except OSError:
            pass

    service_path.write_text(service_content, encoding="utf-8")
    timer_path.write_text(timer_content, encoding="utf-8")
    # Systemd requires 0o644 (rw-r--r--). It silently ignores other perms.
    try:
        os.chmod(str(service_path), 0o644)
        os.chmod(str(timer_path), 0o644)
    except OSError:
        pass

    result["status"] = "installed"
    result["next_action"] = (
        "systemctl --user daemon-reload && "
        "systemctl --user enable --now muninn-prune.timer"
    )
    return result


# ── UNINSTALL — clean removal of hooks + systemd timer ────────────
# CHUNK MCP F.1 (2026-05-12): companion to install_hooks(). Removes
# everything install_hooks() created in `.claude/` + the systemd timer
# from install_cron(). By default leaves `.muninn/` (user data) alone.
# Use --purge-data for the nuclear option.

# The names install_hooks() generates under .claude/hooks/. Anything
# else there is the user's own — we leave it.
_MUNINN_INSTALLED_HOOK_FILES = frozenset({
    "bridge_hook.py",
    "post_tool_failure_hook.py",
    "subagent_start_hook.py",
    "session_start_hook.py",
    "pre_tool_use_bash_destructive.py",
    "pre_tool_use_bash_secrets.py",
    "pre_tool_use_edit_hardcode.py",
    "config_change_hook.py",
    "notification_audit_hook.py",
    "post_tool_use_edit_log.py",
})

# Event names install_hooks() registers in .claude/settings.local.json.
# These are the keys under "hooks" that we'll scrub of muninn-owned entries.
_MUNINN_HOOK_EVENTS = frozenset({
    "UserPromptSubmit",
    "PreCompact",
    "SessionEnd",
    "Stop",
    "PostToolUseFailure",
    "SubagentStart",
    "SessionStart",
    "PreToolUse",
    "PostToolUse",
    "ConfigChange",
    "Notification",
})


def _is_muninn_hook_entry(entry: dict) -> bool:
    """Heuristic: does this hook entry belong to muninn?

    We look for our installed hook filenames in the `command` string or
    for the literal `python -m muninn` invocation (pip-installed mode).
    """
    cmd = entry.get("command", "") if isinstance(entry, dict) else ""
    if not isinstance(cmd, str):
        return False
    # Pip-installed signature
    if "python -m muninn" in cmd or "muninn-mem" in cmd:
        return True
    # File-path signature: any of our installed hook filenames
    for fname in _MUNINN_INSTALLED_HOOK_FILES:
        if fname in cmd:
            return True
    return False


def uninstall_hooks(repo_path, purge_data: bool = False) -> dict:
    """Remove everything Muninn installed in a repo. Companion to install_hooks().

    Steps :
        1. Strip muninn-owned entries from `.claude/settings.local.json` (preserves
           the user's own hooks under the same event names).
        2. Delete `.claude/hooks/*.py` files generated by install_hooks().
        3. Uninstall the systemd-user `muninn-prune.timer` (if present).
        4. If `purge_data=True`, also remove `.muninn/` (user data).
           Default is False — user data is the user's, not ours to delete.

    Returns a dict report (counts of removed items) for the CLI to print.
    """
    repo_path = Path(repo_path).resolve()
    report = {
        "settings_entries_removed": 0,
        "hook_files_removed": [],
        "cron_uninstalled": False,
        "data_purged": False,
        "warnings": [],
    }

    # 1. Strip muninn entries from settings.local.json
    settings_path = repo_path / ".claude" / "settings.local.json"
    if settings_path.exists():
        try:
            settings = json.loads(settings_path.read_text(encoding="utf-8"))
        except Exception as exc:
            report["warnings"].append(
                f"could not parse {settings_path}: {exc}"
            )
            settings = None
        if settings is not None:
            hooks = settings.get("hooks", {})
            removed = 0
            for event_name in list(hooks.keys()):
                if event_name not in _MUNINN_HOOK_EVENTS:
                    continue
                # Two layouts: list of dicts (simple events) OR list of
                # {matcher, hooks: [...]} (PreToolUse/PostToolUse-style).
                entries = hooks[event_name]
                if not isinstance(entries, list):
                    continue
                new_entries = []
                for e in entries:
                    if isinstance(e, dict) and "hooks" in e and isinstance(e["hooks"], list):
                        # Matcher format
                        kept = [h for h in e["hooks"] if not _is_muninn_hook_entry(h)]
                        removed += len(e["hooks"]) - len(kept)
                        if kept:
                            new_entries.append({**e, "hooks": kept})
                    else:
                        if _is_muninn_hook_entry(e):
                            removed += 1
                        else:
                            new_entries.append(e)
                if new_entries:
                    hooks[event_name] = new_entries
                else:
                    # No remaining entries for this event → drop the key entirely
                    del hooks[event_name]
            if removed > 0:
                # Write back atomically
                tmp = settings_path.with_suffix(".json.tmp")
                tmp.write_text(json.dumps(settings, indent=2) + "\n", encoding="utf-8")
                tmp.replace(settings_path)
                report["settings_entries_removed"] = removed

    # 2. Delete hook .py files
    hooks_dir = repo_path / ".claude" / "hooks"
    if hooks_dir.exists():
        for f in sorted(hooks_dir.iterdir()):
            if f.is_file() and f.name in _MUNINN_INSTALLED_HOOK_FILES:
                try:
                    f.unlink()
                    report["hook_files_removed"].append(f.name)
                except Exception as exc:
                    report["warnings"].append(f"could not delete {f}: {exc}")

    # 3. Uninstall systemd timer (delegates to install_cron with uninstall=True)
    try:
        cron_result = install_cron(repo_path, uninstall=True)
        if cron_result.get("removed_files"):
            report["cron_uninstalled"] = True
    except Exception as exc:
        report["warnings"].append(f"install_cron(uninstall=True) failed: {exc}")

    # 4. Optionally purge user data
    if purge_data:
        data_dir = repo_path / ".muninn"
        if data_dir.exists():
            import shutil
            try:
                shutil.rmtree(data_dir)
                report["data_purged"] = True
            except Exception as exc:
                report["warnings"].append(f"could not remove {data_dir}: {exc}")

    return report


# ── SCRUB — universal secret redaction ────────────────────────────
